// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: unified/v1/service.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.unified.v1;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetByDateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:unified.v1.GetByDateRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     * @return The date.
     */
    net.twinte.api.shared.Type.RFC3339FullDate getDate();
  }
  /**
   * Protobuf type {@code unified.v1.GetByDateRequest}
   */
  public  static final class GetByDateRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetByDateRequest, GetByDateRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:unified.v1.GetByDateRequest)
      GetByDateRequestOrBuilder {
    private GetByDateRequest() {
    }
    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private net.twinte.api.shared.Type.RFC3339FullDate date_;
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
      return date_ == null ? net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance() : date_;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      date_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      if (date_ != null &&
          date_ != net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance()) {
        date_ =
          net.twinte.api.shared.Type.RFC3339FullDate.newBuilder(date_).mergeFrom(value).buildPartial();
      } else {
        date_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    private void clearDate() {
      date_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.unified.v1.Service.GetByDateRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code unified.v1.GetByDateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.unified.v1.Service.GetByDateRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:unified.v1.GetByDateRequest)
        net.twinte.api.unified.v1.Service.GetByDateRequestOrBuilder {
      // Construct using net.twinte.api.unified.v1.Service.GetByDateRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      @java.lang.Override
      public boolean hasDate() {
        return instance.hasDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
        return instance.getDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.setDate(value);
        return this;
        }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder setDate(
          net.twinte.api.shared.Type.RFC3339FullDate.Builder builderForValue) {
        copyOnWrite();
        instance.setDate(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.mergeDate(value);
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder clearDate() {  copyOnWrite();
        instance.clearDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:unified.v1.GetByDateRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.unified.v1.Service.GetByDateRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "date_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.unified.v1.Service.GetByDateRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.unified.v1.Service.GetByDateRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.unified.v1.Service.GetByDateRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:unified.v1.GetByDateRequest)
    private static final net.twinte.api.unified.v1.Service.GetByDateRequest DEFAULT_INSTANCE;
    static {
      GetByDateRequest defaultInstance = new GetByDateRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetByDateRequest.class, defaultInstance);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetByDateRequest> PARSER;

    public static com.google.protobuf.Parser<GetByDateRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetByDateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:unified.v1.GetByDateResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    java.util.List<net.twinte.api.schoolcalendar.v1.Type.Event> 
        getEventsList();
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    net.twinte.api.schoolcalendar.v1.Type.Event getEvents(int index);
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    int getEventsCount();

    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     * @return The enum numeric value on the wire for module.
     */
    int getModuleValue();
    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     * @return The module.
     */
    net.twinte.api.schoolcalendar.v1.Type.Module getModule();

    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    java.util.List<net.twinte.api.timetable.v1.Type.RegisteredCourse> 
        getRegisteredCoursesList();
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    net.twinte.api.timetable.v1.Type.RegisteredCourse getRegisteredCourses(int index);
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    int getRegisteredCoursesCount();
  }
  /**
   * Protobuf type {@code unified.v1.GetByDateResponse}
   */
  public  static final class GetByDateResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetByDateResponse, GetByDateResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:unified.v1.GetByDateResponse)
      GetByDateResponseOrBuilder {
    private GetByDateResponse() {
      events_ = emptyProtobufList();
      registeredCourses_ = emptyProtobufList();
    }
    public static final int EVENTS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.schoolcalendar.v1.Type.Event> events_;
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.schoolcalendar.v1.Type.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    public java.util.List<? extends net.twinte.api.schoolcalendar.v1.Type.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.Override
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.Override
    public net.twinte.api.schoolcalendar.v1.Type.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    public net.twinte.api.schoolcalendar.v1.Type.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }
    private void ensureEventsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.schoolcalendar.v1.Type.Event> tmp = events_;
      if (!tmp.isModifiable()) {
        events_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setEvents(
        int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
      value.getClass();  // minimal bytecode null check
      ensureEventsIsMutable();
      events_.set(index, value);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addEvents(net.twinte.api.schoolcalendar.v1.Type.Event value) {
      value.getClass();  // minimal bytecode null check
      ensureEventsIsMutable();
      events_.add(value);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addEvents(
        int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
      value.getClass();  // minimal bytecode null check
      ensureEventsIsMutable();
      events_.add(index, value);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    private void addAllEvents(
        java.lang.Iterable<? extends net.twinte.api.schoolcalendar.v1.Type.Event> values) {
      ensureEventsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, events_);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    private void clearEvents() {
      events_ = emptyProtobufList();
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    private void removeEvents(int index) {
      ensureEventsIsMutable();
      events_.remove(index);
    }

    public static final int MODULE_FIELD_NUMBER = 2;
    private int module_;
    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     * @return The enum numeric value on the wire for module.
     */
    @java.lang.Override
    public int getModuleValue() {
      return module_;
    }
    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     * @return The module.
     */
    @java.lang.Override
    public net.twinte.api.schoolcalendar.v1.Type.Module getModule() {
      net.twinte.api.schoolcalendar.v1.Type.Module result = net.twinte.api.schoolcalendar.v1.Type.Module.forNumber(module_);
      return result == null ? net.twinte.api.schoolcalendar.v1.Type.Module.UNRECOGNIZED : result;
    }
    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     * @param value The enum numeric value on the wire for module to set.
     */
    private void setModuleValue(int value) {
        module_ = value;
    }
    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     * @param value The module to set.
     */
    private void setModule(net.twinte.api.schoolcalendar.v1.Type.Module value) {
      module_ = value.getNumber();

    }
    /**
     * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
     */
    private void clearModule() {

      module_ = 0;
    }

    public static final int REGISTERED_COURSES_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.timetable.v1.Type.RegisteredCourse> registeredCourses_;
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.timetable.v1.Type.RegisteredCourse> getRegisteredCoursesList() {
      return registeredCourses_;
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    public java.util.List<? extends net.twinte.api.timetable.v1.Type.RegisteredCourseOrBuilder> 
        getRegisteredCoursesOrBuilderList() {
      return registeredCourses_;
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    @java.lang.Override
    public int getRegisteredCoursesCount() {
      return registeredCourses_.size();
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    @java.lang.Override
    public net.twinte.api.timetable.v1.Type.RegisteredCourse getRegisteredCourses(int index) {
      return registeredCourses_.get(index);
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    public net.twinte.api.timetable.v1.Type.RegisteredCourseOrBuilder getRegisteredCoursesOrBuilder(
        int index) {
      return registeredCourses_.get(index);
    }
    private void ensureRegisteredCoursesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.timetable.v1.Type.RegisteredCourse> tmp = registeredCourses_;
      if (!tmp.isModifiable()) {
        registeredCourses_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setRegisteredCourses(
        int index, net.twinte.api.timetable.v1.Type.RegisteredCourse value) {
      value.getClass();  // minimal bytecode null check
      ensureRegisteredCoursesIsMutable();
      registeredCourses_.set(index, value);
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addRegisteredCourses(net.twinte.api.timetable.v1.Type.RegisteredCourse value) {
      value.getClass();  // minimal bytecode null check
      ensureRegisteredCoursesIsMutable();
      registeredCourses_.add(value);
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addRegisteredCourses(
        int index, net.twinte.api.timetable.v1.Type.RegisteredCourse value) {
      value.getClass();  // minimal bytecode null check
      ensureRegisteredCoursesIsMutable();
      registeredCourses_.add(index, value);
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    private void addAllRegisteredCourses(
        java.lang.Iterable<? extends net.twinte.api.timetable.v1.Type.RegisteredCourse> values) {
      ensureRegisteredCoursesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, registeredCourses_);
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    private void clearRegisteredCourses() {
      registeredCourses_ = emptyProtobufList();
    }
    /**
     * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
     */
    private void removeRegisteredCourses(int index) {
      ensureRegisteredCoursesIsMutable();
      registeredCourses_.remove(index);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.unified.v1.Service.GetByDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.unified.v1.Service.GetByDateResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code unified.v1.GetByDateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.unified.v1.Service.GetByDateResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:unified.v1.GetByDateResponse)
        net.twinte.api.unified.v1.Service.GetByDateResponseOrBuilder {
      // Construct using net.twinte.api.unified.v1.Service.GetByDateResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.schoolcalendar.v1.Type.Event> getEventsList() {
        return java.util.Collections.unmodifiableList(
            instance.getEventsList());
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      @java.lang.Override
      public int getEventsCount() {
        return instance.getEventsCount();
      }/**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      @java.lang.Override
      public net.twinte.api.schoolcalendar.v1.Type.Event getEvents(int index) {
        return instance.getEvents(index);
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder setEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
        copyOnWrite();
        instance.setEvents(index, value);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder setEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event.Builder builderForValue) {
        copyOnWrite();
        instance.setEvents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(net.twinte.api.schoolcalendar.v1.Type.Event value) {
        copyOnWrite();
        instance.addEvents(value);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
        copyOnWrite();
        instance.addEvents(index, value);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(
          net.twinte.api.schoolcalendar.v1.Type.Event.Builder builderForValue) {
        copyOnWrite();
        instance.addEvents(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event.Builder builderForValue) {
        copyOnWrite();
        instance.addEvents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends net.twinte.api.schoolcalendar.v1.Type.Event> values) {
        copyOnWrite();
        instance.addAllEvents(values);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder clearEvents() {
        copyOnWrite();
        instance.clearEvents();
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder removeEvents(int index) {
        copyOnWrite();
        instance.removeEvents(index);
        return this;
      }

      /**
       * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
       * @return The enum numeric value on the wire for module.
       */
      @java.lang.Override
      public int getModuleValue() {
        return instance.getModuleValue();
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
       * @param value The module to set.
       * @return This builder for chaining.
       */
      public Builder setModuleValue(int value) {
        copyOnWrite();
        instance.setModuleValue(value);
        return this;
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
       * @return The module.
       */
      @java.lang.Override
      public net.twinte.api.schoolcalendar.v1.Type.Module getModule() {
        return instance.getModule();
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
       * @param value The enum numeric value on the wire for module to set.
       * @return This builder for chaining.
       */
      public Builder setModule(net.twinte.api.schoolcalendar.v1.Type.Module value) {
        copyOnWrite();
        instance.setModule(value);
        return this;
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 2 [json_name = "module"];</code>
       * @return This builder for chaining.
       */
      public Builder clearModule() {
        copyOnWrite();
        instance.clearModule();
        return this;
      }

      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.timetable.v1.Type.RegisteredCourse> getRegisteredCoursesList() {
        return java.util.Collections.unmodifiableList(
            instance.getRegisteredCoursesList());
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      @java.lang.Override
      public int getRegisteredCoursesCount() {
        return instance.getRegisteredCoursesCount();
      }/**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      @java.lang.Override
      public net.twinte.api.timetable.v1.Type.RegisteredCourse getRegisteredCourses(int index) {
        return instance.getRegisteredCourses(index);
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder setRegisteredCourses(
          int index, net.twinte.api.timetable.v1.Type.RegisteredCourse value) {
        copyOnWrite();
        instance.setRegisteredCourses(index, value);
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder setRegisteredCourses(
          int index, net.twinte.api.timetable.v1.Type.RegisteredCourse.Builder builderForValue) {
        copyOnWrite();
        instance.setRegisteredCourses(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder addRegisteredCourses(net.twinte.api.timetable.v1.Type.RegisteredCourse value) {
        copyOnWrite();
        instance.addRegisteredCourses(value);
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder addRegisteredCourses(
          int index, net.twinte.api.timetable.v1.Type.RegisteredCourse value) {
        copyOnWrite();
        instance.addRegisteredCourses(index, value);
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder addRegisteredCourses(
          net.twinte.api.timetable.v1.Type.RegisteredCourse.Builder builderForValue) {
        copyOnWrite();
        instance.addRegisteredCourses(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder addRegisteredCourses(
          int index, net.twinte.api.timetable.v1.Type.RegisteredCourse.Builder builderForValue) {
        copyOnWrite();
        instance.addRegisteredCourses(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder addAllRegisteredCourses(
          java.lang.Iterable<? extends net.twinte.api.timetable.v1.Type.RegisteredCourse> values) {
        copyOnWrite();
        instance.addAllRegisteredCourses(values);
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder clearRegisteredCourses() {
        copyOnWrite();
        instance.clearRegisteredCourses();
        return this;
      }
      /**
       * <code>repeated .timetable.v1.RegisteredCourse registered_courses = 3 [json_name = "registeredCourses"];</code>
       */
      public Builder removeRegisteredCourses(int index) {
        copyOnWrite();
        instance.removeRegisteredCourses(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:unified.v1.GetByDateResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.unified.v1.Service.GetByDateResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "events_",
              net.twinte.api.schoolcalendar.v1.Type.Event.class,
              "module_",
              "registeredCourses_",
              net.twinte.api.timetable.v1.Type.RegisteredCourse.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0002\u0000\u0001\u001b\u0002\f" +
                "\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.unified.v1.Service.GetByDateResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.unified.v1.Service.GetByDateResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.unified.v1.Service.GetByDateResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:unified.v1.GetByDateResponse)
    private static final net.twinte.api.unified.v1.Service.GetByDateResponse DEFAULT_INSTANCE;
    static {
      GetByDateResponse defaultInstance = new GetByDateResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetByDateResponse.class, defaultInstance);
    }

    public static net.twinte.api.unified.v1.Service.GetByDateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetByDateResponse> PARSER;

    public static com.google.protobuf.Parser<GetByDateResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
