// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: unified/v1/service.proto
//
package net.twinte.api.unified.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The following error codes are not stated explicitly in the each rpc, but may be returned.
 *    - shared.InvalidArgument
 *    - shared.Unauthenticated
 *    - shared.Unauthorized
 */
public interface UnifiedServiceClientInterface {
  /**
   *  GetByDate returns the resources related to the given date.
   *  Only registered courses which will be held on the given date will be returned.
   */
  public suspend fun getByDate(request: Service.GetByDateRequest, headers: Headers = emptyMap()): ResponseMessage<Service.GetByDateResponse>
}
