// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: unified/v1/service.proto
//
package net.twinte.api.unified.v1

import com.connectrpc.Headers
import com.connectrpc.Idempotency
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  The following error codes are not stated explicitly in the each rpc, but may be returned.
 *    - shared.InvalidArgument
 *    - shared.Unauthenticated
 *    - shared.Unauthorized
 */
public class UnifiedServiceClient(
  private val client: ProtocolClientInterface,
) : UnifiedServiceClientInterface {
  /**
   *  GetByDate returns the resources related to the given date.
   *  Only registered courses which will be held on the given date will be returned.
   */
  override suspend fun getByDate(request: Service.GetByDateRequest, headers: Headers): ResponseMessage<Service.GetByDateResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "unified.v1.UnifiedService/GetByDate",
      net.twinte.api.unified.v1.Service.GetByDateRequest::class,
      net.twinte.api.unified.v1.Service.GetByDateResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.NO_SIDE_EFFECTS,
    ),
  )

}
