// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/option.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.shared;

public final class Option {
  private Option() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(net.twinte.api.shared.Option.twinte);
  }
  /**
   * Protobuf enum {@code shared.Authentication}
   */
  public enum Authentication
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>AUTHENTICATION_UNSPECIFIED = 0;</code>
     */
    AUTHENTICATION_UNSPECIFIED(0),
    /**
     * <code>NOT_REQURED = 1;</code>
     */
    NOT_REQURED(1),
    /**
     * <code>OPTIONAL = 2;</code>
     */
    OPTIONAL(2),
    /**
     * <code>REQURED = 3;</code>
     */
    REQURED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AUTHENTICATION_UNSPECIFIED = 0;</code>
     */
    public static final int AUTHENTICATION_UNSPECIFIED_VALUE = 0;
    /**
     * <code>NOT_REQURED = 1;</code>
     */
    public static final int NOT_REQURED_VALUE = 1;
    /**
     * <code>OPTIONAL = 2;</code>
     */
    public static final int OPTIONAL_VALUE = 2;
    /**
     * <code>REQURED = 3;</code>
     */
    public static final int REQURED_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Authentication valueOf(int value) {
      return forNumber(value);
    }

    public static Authentication forNumber(int value) {
      switch (value) {
        case 0: return AUTHENTICATION_UNSPECIFIED;
        case 1: return NOT_REQURED;
        case 2: return OPTIONAL;
        case 3: return REQURED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Authentication>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Authentication> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Authentication>() {
            @java.lang.Override
            public Authentication findValueByNumber(int number) {
              return Authentication.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return AuthenticationVerifier.INSTANCE;
    }

    private static final class AuthenticationVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new AuthenticationVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Authentication.forNumber(number) != null;
            }
          };

    private final int value;

    private Authentication(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:shared.Authentication)
  }

  public interface TwinteMethodOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.TwinteMethodOptions)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     * @return The enum numeric value on the wire for authentication.
     */
    int getAuthenticationValue();
    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     * @return The authentication.
     */
    net.twinte.api.shared.Option.Authentication getAuthentication();

    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @return A list containing the errorCodes.
     */
    java.util.List<java.lang.String>
        getErrorCodesList();
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @return The count of errorCodes.
     */
    int getErrorCodesCount();
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param index The index of the element to return.
     * @return The errorCodes at the given index.
     */
    java.lang.String getErrorCodes(int index);
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param index The index of the element to return.
     * @return The errorCodes at the given index.
     */
    com.google.protobuf.ByteString
        getErrorCodesBytes(int index);
  }
  /**
   * Protobuf type {@code shared.TwinteMethodOptions}
   */
  public  static final class TwinteMethodOptions extends
      com.google.protobuf.GeneratedMessageLite<
          TwinteMethodOptions, TwinteMethodOptions.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.TwinteMethodOptions)
      TwinteMethodOptionsOrBuilder {
    private TwinteMethodOptions() {
      errorCodes_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int AUTHENTICATION_FIELD_NUMBER = 1;
    private int authentication_;
    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     * @return The enum numeric value on the wire for authentication.
     */
    @java.lang.Override
    public int getAuthenticationValue() {
      return authentication_;
    }
    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     * @return The authentication.
     */
    @java.lang.Override
    public net.twinte.api.shared.Option.Authentication getAuthentication() {
      net.twinte.api.shared.Option.Authentication result = net.twinte.api.shared.Option.Authentication.forNumber(authentication_);
      return result == null ? net.twinte.api.shared.Option.Authentication.UNRECOGNIZED : result;
    }
    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     * @param value The enum numeric value on the wire for authentication to set.
     */
    private void setAuthenticationValue(int value) {
        authentication_ = value;
    }
    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     * @param value The authentication to set.
     */
    private void setAuthentication(net.twinte.api.shared.Option.Authentication value) {
      authentication_ = value.getNumber();

    }
    /**
     * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
     */
    private void clearAuthentication() {

      authentication_ = 0;
    }

    public static final int ERROR_CODES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> errorCodes_;
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @return A list containing the errorCodes.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getErrorCodesList() {
      return errorCodes_;
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @return The count of errorCodes.
     */
    @java.lang.Override
    public int getErrorCodesCount() {
      return errorCodes_.size();
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param index The index of the element to return.
     * @return The errorCodes at the given index.
     */
    @java.lang.Override
    public java.lang.String getErrorCodes(int index) {
      return errorCodes_.get(index);
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the errorCodes at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorCodesBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          errorCodes_.get(index));
    }
    private void ensureErrorCodesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
          errorCodes_;  if (!tmp.isModifiable()) {
        errorCodes_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param index The index to set the value at.
     * @param value The errorCodes to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setErrorCodes(
        int index, java.lang.String value) {
      value.getClass();  // minimal bytecode null check
      ensureErrorCodesIsMutable();
      errorCodes_.set(index, value);
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param value The errorCodes to add.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addErrorCodes(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check
      ensureErrorCodesIsMutable();
      errorCodes_.add(value);
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param values The errorCodes to add.
     */
    private void addAllErrorCodes(
        java.lang.Iterable<java.lang.String> values) {
      ensureErrorCodesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, errorCodes_);
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     */
    private void clearErrorCodes() {
      errorCodes_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
     * @param value The bytes of the errorCodes to add.
     */
    private void addErrorCodesBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      ensureErrorCodesIsMutable();
      errorCodes_.add(value.toStringUtf8());
    }

    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Option.TwinteMethodOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Option.TwinteMethodOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Option.TwinteMethodOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Option.TwinteMethodOptions prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code shared.TwinteMethodOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Option.TwinteMethodOptions, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.TwinteMethodOptions)
        net.twinte.api.shared.Option.TwinteMethodOptionsOrBuilder {
      // Construct using net.twinte.api.shared.Option.TwinteMethodOptions.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
       * @return The enum numeric value on the wire for authentication.
       */
      @java.lang.Override
      public int getAuthenticationValue() {
        return instance.getAuthenticationValue();
      }
      /**
       * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
       * @param value The authentication to set.
       * @return This builder for chaining.
       */
      public Builder setAuthenticationValue(int value) {
        copyOnWrite();
        instance.setAuthenticationValue(value);
        return this;
      }
      /**
       * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
       * @return The authentication.
       */
      @java.lang.Override
      public net.twinte.api.shared.Option.Authentication getAuthentication() {
        return instance.getAuthentication();
      }
      /**
       * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
       * @param value The enum numeric value on the wire for authentication to set.
       * @return This builder for chaining.
       */
      public Builder setAuthentication(net.twinte.api.shared.Option.Authentication value) {
        copyOnWrite();
        instance.setAuthentication(value);
        return this;
      }
      /**
       * <code>.shared.Authentication authentication = 1 [json_name = "authentication"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthentication() {
        copyOnWrite();
        instance.clearAuthentication();
        return this;
      }

      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @return A list containing the errorCodes.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getErrorCodesList() {
        return java.util.Collections.unmodifiableList(
            instance.getErrorCodesList());
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @return The count of errorCodes.
       */
      @java.lang.Override
      public int getErrorCodesCount() {
        return instance.getErrorCodesCount();
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @param index The index of the element to return.
       * @return The errorCodes at the given index.
       */
      @java.lang.Override
      public java.lang.String getErrorCodes(int index) {
        return instance.getErrorCodes(index);
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @param index The index of the value to return.
       * @return The bytes of the errorCodes at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrorCodesBytes(int index) {
        return instance.getErrorCodesBytes(index);
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @param index The index to set the value at.
       * @param value The errorCodes to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodes(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setErrorCodes(index, value);
        return this;
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @param value The errorCodes to add.
       * @return This builder for chaining.
       */
      public Builder addErrorCodes(
          java.lang.String value) {
        copyOnWrite();
        instance.addErrorCodes(value);
        return this;
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @param values The errorCodes to add.
       * @return This builder for chaining.
       */
      public Builder addAllErrorCodes(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllErrorCodes(values);
        return this;
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCodes() {
        copyOnWrite();
        instance.clearErrorCodes();
        return this;
      }
      /**
       * <code>repeated string error_codes = 2 [json_name = "errorCodes"];</code>
       * @param value The bytes of the errorCodes to add.
       * @return This builder for chaining.
       */
      public Builder addErrorCodesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addErrorCodesBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.TwinteMethodOptions)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Option.TwinteMethodOptions();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "authentication_",
              "errorCodes_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\f\u0002\u021a" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Option.TwinteMethodOptions> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Option.TwinteMethodOptions.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Option.TwinteMethodOptions>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.TwinteMethodOptions)
    private static final net.twinte.api.shared.Option.TwinteMethodOptions DEFAULT_INSTANCE;
    static {
      TwinteMethodOptions defaultInstance = new TwinteMethodOptions();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        TwinteMethodOptions.class, defaultInstance);
    }

    public static net.twinte.api.shared.Option.TwinteMethodOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TwinteMethodOptions> PARSER;

    public static com.google.protobuf.Parser<TwinteMethodOptions> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int TWINTE_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      net.twinte.api.shared.Option.TwinteMethodOptions> twinte = com.google.protobuf.GeneratedMessageLite
          .newSingularGeneratedExtension(
        com.google.protobuf.DescriptorProtos.MethodOptions.getDefaultInstance(),
        net.twinte.api.shared.Option.TwinteMethodOptions.getDefaultInstance(),
        net.twinte.api.shared.Option.TwinteMethodOptions.getDefaultInstance(),
        null,
        50000,
        com.google.protobuf.WireFormat.FieldType.MESSAGE,
        net.twinte.api.shared.Option.TwinteMethodOptions.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
