// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/type.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.shared;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code shared.Weekday}
   */
  public enum Weekday
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>WEEKDAY_UNSPECIFIED = 0;</code>
     */
    WEEKDAY_UNSPECIFIED(0),
    /**
     * <code>WEEKDAY_SUNDAY = 1;</code>
     */
    WEEKDAY_SUNDAY(1),
    /**
     * <code>WEEKDAY_MONDAY = 2;</code>
     */
    WEEKDAY_MONDAY(2),
    /**
     * <code>WEEKDAY_TUESDAY = 3;</code>
     */
    WEEKDAY_TUESDAY(3),
    /**
     * <code>WEEKDAY_WEDNESDAY = 4;</code>
     */
    WEEKDAY_WEDNESDAY(4),
    /**
     * <code>WEEKDAY_THURSDAY = 5;</code>
     */
    WEEKDAY_THURSDAY(5),
    /**
     * <code>WEEKDAY_FRIDAY = 6;</code>
     */
    WEEKDAY_FRIDAY(6),
    /**
     * <code>WEEKDAY_SATURDAY = 7;</code>
     */
    WEEKDAY_SATURDAY(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WEEKDAY_UNSPECIFIED = 0;</code>
     */
    public static final int WEEKDAY_UNSPECIFIED_VALUE = 0;
    /**
     * <code>WEEKDAY_SUNDAY = 1;</code>
     */
    public static final int WEEKDAY_SUNDAY_VALUE = 1;
    /**
     * <code>WEEKDAY_MONDAY = 2;</code>
     */
    public static final int WEEKDAY_MONDAY_VALUE = 2;
    /**
     * <code>WEEKDAY_TUESDAY = 3;</code>
     */
    public static final int WEEKDAY_TUESDAY_VALUE = 3;
    /**
     * <code>WEEKDAY_WEDNESDAY = 4;</code>
     */
    public static final int WEEKDAY_WEDNESDAY_VALUE = 4;
    /**
     * <code>WEEKDAY_THURSDAY = 5;</code>
     */
    public static final int WEEKDAY_THURSDAY_VALUE = 5;
    /**
     * <code>WEEKDAY_FRIDAY = 6;</code>
     */
    public static final int WEEKDAY_FRIDAY_VALUE = 6;
    /**
     * <code>WEEKDAY_SATURDAY = 7;</code>
     */
    public static final int WEEKDAY_SATURDAY_VALUE = 7;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Weekday valueOf(int value) {
      return forNumber(value);
    }

    public static Weekday forNumber(int value) {
      switch (value) {
        case 0: return WEEKDAY_UNSPECIFIED;
        case 1: return WEEKDAY_SUNDAY;
        case 2: return WEEKDAY_MONDAY;
        case 3: return WEEKDAY_TUESDAY;
        case 4: return WEEKDAY_WEDNESDAY;
        case 5: return WEEKDAY_THURSDAY;
        case 6: return WEEKDAY_FRIDAY;
        case 7: return WEEKDAY_SATURDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Weekday>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Weekday> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Weekday>() {
            @java.lang.Override
            public Weekday findValueByNumber(int number) {
              return Weekday.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return WeekdayVerifier.INSTANCE;
    }

    private static final class WeekdayVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new WeekdayVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Weekday.forNumber(number) != null;
            }
          };

    private final int value;

    private Weekday(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:shared.Weekday)
  }

  public interface OptionalStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.OptionalString)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code shared.OptionalString}
   */
  public  static final class OptionalString extends
      com.google.protobuf.GeneratedMessageLite<
          OptionalString, OptionalString.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.OptionalString)
      OptionalStringOrBuilder {
    private OptionalString() {
      value_ = "";
    }
    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.String value_;
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @param value The value to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check
      bitField0_ |= 0x00000001;
      value_ = value;
    }
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     */
    private void clearValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>optional string value = 1 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Type.OptionalString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Type.OptionalString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.OptionalString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Type.OptionalString prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code shared.OptionalString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Type.OptionalString, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.OptionalString)
        net.twinte.api.shared.Type.OptionalStringOrBuilder {
      // Construct using net.twinte.api.shared.Type.OptionalString.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string value = 1 [json_name = "value"];</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return instance.hasValue();
      }
      /**
       * <code>optional string value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>optional string value = 1 [json_name = "value"];</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>optional string value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>optional string value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>optional string value = 1 [json_name = "value"];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.OptionalString)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Type.OptionalString();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1208\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Type.OptionalString> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Type.OptionalString.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Type.OptionalString>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.OptionalString)
    private static final net.twinte.api.shared.Type.OptionalString DEFAULT_INSTANCE;
    static {
      OptionalString defaultInstance = new OptionalString();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OptionalString.class, defaultInstance);
    }

    public static net.twinte.api.shared.Type.OptionalString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OptionalString> PARSER;

    public static com.google.protobuf.Parser<OptionalString> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AcademicYearOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.AcademicYear)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    int getValue();
  }
  /**
   * Protobuf type {@code shared.AcademicYear}
   */
  public  static final class AcademicYear extends
      com.google.protobuf.GeneratedMessageLite<
          AcademicYear, AcademicYear.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.AcademicYear)
      AcademicYearOrBuilder {
    private AcademicYear() {
    }
    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>int32 value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }
    /**
     * <code>int32 value = 1 [json_name = "value"];</code>
     * @param value The value to set.
     */
    private void setValue(int value) {
      
      value_ = value;
    }
    /**
     * <code>int32 value = 1 [json_name = "value"];</code>
     */
    private void clearValue() {

      value_ = 0;
    }

    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Type.AcademicYear parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Type.AcademicYear parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.AcademicYear parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Type.AcademicYear prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code shared.AcademicYear}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Type.AcademicYear, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.AcademicYear)
        net.twinte.api.shared.Type.AcademicYearOrBuilder {
      // Construct using net.twinte.api.shared.Type.AcademicYear.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public int getValue() {
        return instance.getValue();
      }
      /**
       * <code>int32 value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(int value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>int32 value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.AcademicYear)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Type.AcademicYear();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "value_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Type.AcademicYear> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Type.AcademicYear.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Type.AcademicYear>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.AcademicYear)
    private static final net.twinte.api.shared.Type.AcademicYear DEFAULT_INSTANCE;
    static {
      AcademicYear defaultInstance = new AcademicYear();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AcademicYear.class, defaultInstance);
    }

    public static net.twinte.api.shared.Type.AcademicYear getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AcademicYear> PARSER;

    public static com.google.protobuf.Parser<AcademicYear> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UUIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.UUID)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code shared.UUID}
   */
  public  static final class UUID extends
      com.google.protobuf.GeneratedMessageLite<
          UUID, UUID.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.UUID)
      UUIDOrBuilder {
    private UUID() {
      value_ = "";
    }
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.String value_;
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @param value The value to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      value_ = value;
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static net.twinte.api.shared.Type.UUID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Type.UUID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Type.UUID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.UUID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Type.UUID prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code shared.UUID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Type.UUID, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.UUID)
        net.twinte.api.shared.Type.UUIDOrBuilder {
      // Construct using net.twinte.api.shared.Type.UUID.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.UUID)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Type.UUID();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "value_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Type.UUID> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Type.UUID.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Type.UUID>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.UUID)
    private static final net.twinte.api.shared.Type.UUID DEFAULT_INSTANCE;
    static {
      UUID defaultInstance = new UUID();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UUID.class, defaultInstance);
    }

    public static net.twinte.api.shared.Type.UUID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UUID> PARSER;

    public static com.google.protobuf.Parser<UUID> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UUIDListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.UUIDList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    java.util.List<net.twinte.api.shared.Type.UUID> 
        getValuesList();
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    net.twinte.api.shared.Type.UUID getValues(int index);
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    int getValuesCount();
  }
  /**
   * Protobuf type {@code shared.UUIDList}
   */
  public  static final class UUIDList extends
      com.google.protobuf.GeneratedMessageLite<
          UUIDList, UUIDList.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.UUIDList)
      UUIDListOrBuilder {
    private UUIDList() {
      values_ = emptyProtobufList();
    }
    public static final int VALUES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.shared.Type.UUID> values_;
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.shared.Type.UUID> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    public java.util.List<? extends net.twinte.api.shared.Type.UUIDOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.UUID getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    public net.twinte.api.shared.Type.UUIDOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }
    private void ensureValuesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.shared.Type.UUID> tmp = values_;
      if (!tmp.isModifiable()) {
        values_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValues(
        int index, net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      ensureValuesIsMutable();
      values_.set(index, value);
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addValues(net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      ensureValuesIsMutable();
      values_.add(value);
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addValues(
        int index, net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      ensureValuesIsMutable();
      values_.add(index, value);
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    private void addAllValues(
        java.lang.Iterable<? extends net.twinte.api.shared.Type.UUID> values) {
      ensureValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, values_);
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    private void clearValues() {
      values_ = emptyProtobufList();
    }
    /**
     * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
     */
    private void removeValues(int index) {
      ensureValuesIsMutable();
      values_.remove(index);
    }

    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Type.UUIDList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Type.UUIDList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.UUIDList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Type.UUIDList prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code shared.UUIDList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Type.UUIDList, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.UUIDList)
        net.twinte.api.shared.Type.UUIDListOrBuilder {
      // Construct using net.twinte.api.shared.Type.UUIDList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.shared.Type.UUID> getValuesList() {
        return java.util.Collections.unmodifiableList(
            instance.getValuesList());
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      @java.lang.Override
      public int getValuesCount() {
        return instance.getValuesCount();
      }/**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.UUID getValues(int index) {
        return instance.getValues(index);
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder setValues(
          int index, net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.setValues(index, value);
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder setValues(
          int index, net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.setValues(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder addValues(net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.addValues(value);
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder addValues(
          int index, net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.addValues(index, value);
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder addValues(
          net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.addValues(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder addValues(
          int index, net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.addValues(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends net.twinte.api.shared.Type.UUID> values) {
        copyOnWrite();
        instance.addAllValues(values);
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder clearValues() {
        copyOnWrite();
        instance.clearValues();
        return this;
      }
      /**
       * <code>repeated .shared.UUID values = 1 [json_name = "values"];</code>
       */
      public Builder removeValues(int index) {
        copyOnWrite();
        instance.removeValues(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.UUIDList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Type.UUIDList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "values_",
              net.twinte.api.shared.Type.UUID.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Type.UUIDList> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Type.UUIDList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Type.UUIDList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.UUIDList)
    private static final net.twinte.api.shared.Type.UUIDList DEFAULT_INSTANCE;
    static {
      UUIDList defaultInstance = new UUIDList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UUIDList.class, defaultInstance);
    }

    public static net.twinte.api.shared.Type.UUIDList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UUIDList> PARSER;

    public static com.google.protobuf.Parser<UUIDList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RFC3339FullDateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.RFC3339FullDate)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * e.g. 2006-01-02
   * </pre>
   *
   * Protobuf type {@code shared.RFC3339FullDate}
   */
  public  static final class RFC3339FullDate extends
      com.google.protobuf.GeneratedMessageLite<
          RFC3339FullDate, RFC3339FullDate.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.RFC3339FullDate)
      RFC3339FullDateOrBuilder {
    private RFC3339FullDate() {
      value_ = "";
    }
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.String value_;
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @param value The value to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      value_ = value;
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Type.RFC3339FullDate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Type.RFC3339FullDate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.RFC3339FullDate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Type.RFC3339FullDate prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * e.g. 2006-01-02
     * </pre>
     *
     * Protobuf type {@code shared.RFC3339FullDate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Type.RFC3339FullDate, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.RFC3339FullDate)
        net.twinte.api.shared.Type.RFC3339FullDateOrBuilder {
      // Construct using net.twinte.api.shared.Type.RFC3339FullDate.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.RFC3339FullDate)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Type.RFC3339FullDate();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "value_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Type.RFC3339FullDate> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Type.RFC3339FullDate.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Type.RFC3339FullDate>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.RFC3339FullDate)
    private static final net.twinte.api.shared.Type.RFC3339FullDate DEFAULT_INSTANCE;
    static {
      RFC3339FullDate defaultInstance = new RFC3339FullDate();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RFC3339FullDate.class, defaultInstance);
    }

    public static net.twinte.api.shared.Type.RFC3339FullDate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RFC3339FullDate> PARSER;

    public static com.google.protobuf.Parser<RFC3339FullDate> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RFC3339DateTimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shared.RFC3339DateTime)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   * e.g. 2006-01-02T15:04:05.999999+09:00
   * </pre>
   *
   * Protobuf type {@code shared.RFC3339DateTime}
   */
  public  static final class RFC3339DateTime extends
      com.google.protobuf.GeneratedMessageLite<
          RFC3339DateTime, RFC3339DateTime.Builder> implements
      // @@protoc_insertion_point(message_implements:shared.RFC3339DateTime)
      RFC3339DateTimeOrBuilder {
    private RFC3339DateTime() {
      value_ = "";
    }
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.String value_;
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @param value The value to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setValue(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      value_ = value;
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.shared.Type.RFC3339DateTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.shared.Type.RFC3339DateTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.shared.Type.RFC3339DateTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.shared.Type.RFC3339DateTime prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * e.g. 2006-01-02T15:04:05.999999+09:00
     * </pre>
     *
     * Protobuf type {@code shared.RFC3339DateTime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.shared.Type.RFC3339DateTime, Builder> implements
        // @@protoc_insertion_point(builder_implements:shared.RFC3339DateTime)
        net.twinte.api.shared.Type.RFC3339DateTimeOrBuilder {
      // Construct using net.twinte.api.shared.Type.RFC3339DateTime.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:shared.RFC3339DateTime)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.shared.Type.RFC3339DateTime();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "value_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.shared.Type.RFC3339DateTime> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.shared.Type.RFC3339DateTime.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.shared.Type.RFC3339DateTime>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:shared.RFC3339DateTime)
    private static final net.twinte.api.shared.Type.RFC3339DateTime DEFAULT_INSTANCE;
    static {
      RFC3339DateTime defaultInstance = new RFC3339DateTime();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RFC3339DateTime.class, defaultInstance);
    }

    public static net.twinte.api.shared.Type.RFC3339DateTime getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RFC3339DateTime> PARSER;

    public static com.google.protobuf.Parser<RFC3339DateTime> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
