// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: announcement/v1/service.proto
//
package net.twinte.api.announcement.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The following error codes are not stated explicitly in the each rpc, but may be returned.
 *    - shared.InvalidArgument
 *    - shared.Unauthenticated
 *    - shared.Unauthorized
 */
public interface AnnouncementServiceClientInterface {
  public suspend fun listAnnouncements(request: Service.ListAnnouncementsRequest, headers: Headers = emptyMap()): ResponseMessage<Service.ListAnnouncementsResponse>

  public suspend fun readAnnouncements(request: Service.ReadAnnouncementsRequest, headers: Headers = emptyMap()): ResponseMessage<Service.ReadAnnouncementsResponse>
}
