// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: announcement/v1/service.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.announcement.v1;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ListAnnouncementsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:announcement.v1.ListAnnouncementsRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code announcement.v1.ListAnnouncementsRequest}
   */
  public  static final class ListAnnouncementsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ListAnnouncementsRequest, ListAnnouncementsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:announcement.v1.ListAnnouncementsRequest)
      ListAnnouncementsRequestOrBuilder {
    private ListAnnouncementsRequest() {
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code announcement.v1.ListAnnouncementsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:announcement.v1.ListAnnouncementsRequest)
        net.twinte.api.announcement.v1.Service.ListAnnouncementsRequestOrBuilder {
      // Construct using net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:announcement.v1.ListAnnouncementsRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:announcement.v1.ListAnnouncementsRequest)
    private static final net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest DEFAULT_INSTANCE;
    static {
      ListAnnouncementsRequest defaultInstance = new ListAnnouncementsRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ListAnnouncementsRequest.class, defaultInstance);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ListAnnouncementsRequest> PARSER;

    public static com.google.protobuf.Parser<ListAnnouncementsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ListAnnouncementsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:announcement.v1.ListAnnouncementsResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    java.util.List<net.twinte.api.announcement.v1.Type.Announcement> 
        getAnnouncementsList();
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    net.twinte.api.announcement.v1.Type.Announcement getAnnouncements(int index);
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    int getAnnouncementsCount();
  }
  /**
   * Protobuf type {@code announcement.v1.ListAnnouncementsResponse}
   */
  public  static final class ListAnnouncementsResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ListAnnouncementsResponse, ListAnnouncementsResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:announcement.v1.ListAnnouncementsResponse)
      ListAnnouncementsResponseOrBuilder {
    private ListAnnouncementsResponse() {
      announcements_ = emptyProtobufList();
    }
    public static final int ANNOUNCEMENTS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.announcement.v1.Type.Announcement> announcements_;
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.announcement.v1.Type.Announcement> getAnnouncementsList() {
      return announcements_;
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    public java.util.List<? extends net.twinte.api.announcement.v1.Type.AnnouncementOrBuilder> 
        getAnnouncementsOrBuilderList() {
      return announcements_;
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    @java.lang.Override
    public int getAnnouncementsCount() {
      return announcements_.size();
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    @java.lang.Override
    public net.twinte.api.announcement.v1.Type.Announcement getAnnouncements(int index) {
      return announcements_.get(index);
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    public net.twinte.api.announcement.v1.Type.AnnouncementOrBuilder getAnnouncementsOrBuilder(
        int index) {
      return announcements_.get(index);
    }
    private void ensureAnnouncementsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.announcement.v1.Type.Announcement> tmp = announcements_;
      if (!tmp.isModifiable()) {
        announcements_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setAnnouncements(
        int index, net.twinte.api.announcement.v1.Type.Announcement value) {
      value.getClass();  // minimal bytecode null check
      ensureAnnouncementsIsMutable();
      announcements_.set(index, value);
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addAnnouncements(net.twinte.api.announcement.v1.Type.Announcement value) {
      value.getClass();  // minimal bytecode null check
      ensureAnnouncementsIsMutable();
      announcements_.add(value);
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addAnnouncements(
        int index, net.twinte.api.announcement.v1.Type.Announcement value) {
      value.getClass();  // minimal bytecode null check
      ensureAnnouncementsIsMutable();
      announcements_.add(index, value);
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    private void addAllAnnouncements(
        java.lang.Iterable<? extends net.twinte.api.announcement.v1.Type.Announcement> values) {
      ensureAnnouncementsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, announcements_);
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    private void clearAnnouncements() {
      announcements_ = emptyProtobufList();
    }
    /**
     * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
     */
    private void removeAnnouncements(int index) {
      ensureAnnouncementsIsMutable();
      announcements_.remove(index);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code announcement.v1.ListAnnouncementsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:announcement.v1.ListAnnouncementsResponse)
        net.twinte.api.announcement.v1.Service.ListAnnouncementsResponseOrBuilder {
      // Construct using net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.announcement.v1.Type.Announcement> getAnnouncementsList() {
        return java.util.Collections.unmodifiableList(
            instance.getAnnouncementsList());
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      @java.lang.Override
      public int getAnnouncementsCount() {
        return instance.getAnnouncementsCount();
      }/**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      @java.lang.Override
      public net.twinte.api.announcement.v1.Type.Announcement getAnnouncements(int index) {
        return instance.getAnnouncements(index);
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder setAnnouncements(
          int index, net.twinte.api.announcement.v1.Type.Announcement value) {
        copyOnWrite();
        instance.setAnnouncements(index, value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder setAnnouncements(
          int index, net.twinte.api.announcement.v1.Type.Announcement.Builder builderForValue) {
        copyOnWrite();
        instance.setAnnouncements(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder addAnnouncements(net.twinte.api.announcement.v1.Type.Announcement value) {
        copyOnWrite();
        instance.addAnnouncements(value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder addAnnouncements(
          int index, net.twinte.api.announcement.v1.Type.Announcement value) {
        copyOnWrite();
        instance.addAnnouncements(index, value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder addAnnouncements(
          net.twinte.api.announcement.v1.Type.Announcement.Builder builderForValue) {
        copyOnWrite();
        instance.addAnnouncements(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder addAnnouncements(
          int index, net.twinte.api.announcement.v1.Type.Announcement.Builder builderForValue) {
        copyOnWrite();
        instance.addAnnouncements(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder addAllAnnouncements(
          java.lang.Iterable<? extends net.twinte.api.announcement.v1.Type.Announcement> values) {
        copyOnWrite();
        instance.addAllAnnouncements(values);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder clearAnnouncements() {
        copyOnWrite();
        instance.clearAnnouncements();
        return this;
      }
      /**
       * <code>repeated .announcement.v1.Announcement announcements = 1 [json_name = "announcements"];</code>
       */
      public Builder removeAnnouncements(int index) {
        copyOnWrite();
        instance.removeAnnouncements(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:announcement.v1.ListAnnouncementsResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "announcements_",
              net.twinte.api.announcement.v1.Type.Announcement.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:announcement.v1.ListAnnouncementsResponse)
    private static final net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse DEFAULT_INSTANCE;
    static {
      ListAnnouncementsResponse defaultInstance = new ListAnnouncementsResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ListAnnouncementsResponse.class, defaultInstance);
    }

    public static net.twinte.api.announcement.v1.Service.ListAnnouncementsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ListAnnouncementsResponse> PARSER;

    public static com.google.protobuf.Parser<ListAnnouncementsResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ReadAnnouncementsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:announcement.v1.ReadAnnouncementsRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    java.util.List<net.twinte.api.shared.Type.UUID> 
        getIdsList();
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    net.twinte.api.shared.Type.UUID getIds(int index);
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    int getIdsCount();
  }
  /**
   * Protobuf type {@code announcement.v1.ReadAnnouncementsRequest}
   */
  public  static final class ReadAnnouncementsRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ReadAnnouncementsRequest, ReadAnnouncementsRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:announcement.v1.ReadAnnouncementsRequest)
      ReadAnnouncementsRequestOrBuilder {
    private ReadAnnouncementsRequest() {
      ids_ = emptyProtobufList();
    }
    public static final int IDS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.shared.Type.UUID> ids_;
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.shared.Type.UUID> getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    public java.util.List<? extends net.twinte.api.shared.Type.UUIDOrBuilder> 
        getIdsOrBuilderList() {
      return ids_;
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    @java.lang.Override
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.UUID getIds(int index) {
      return ids_.get(index);
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    public net.twinte.api.shared.Type.UUIDOrBuilder getIdsOrBuilder(
        int index) {
      return ids_.get(index);
    }
    private void ensureIdsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.shared.Type.UUID> tmp = ids_;
      if (!tmp.isModifiable()) {
        ids_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setIds(
        int index, net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      ensureIdsIsMutable();
      ids_.set(index, value);
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addIds(net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      ensureIdsIsMutable();
      ids_.add(value);
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addIds(
        int index, net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      ensureIdsIsMutable();
      ids_.add(index, value);
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    private void addAllIds(
        java.lang.Iterable<? extends net.twinte.api.shared.Type.UUID> values) {
      ensureIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, ids_);
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    private void clearIds() {
      ids_ = emptyProtobufList();
    }
    /**
     * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
     */
    private void removeIds(int index) {
      ensureIdsIsMutable();
      ids_.remove(index);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code announcement.v1.ReadAnnouncementsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:announcement.v1.ReadAnnouncementsRequest)
        net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequestOrBuilder {
      // Construct using net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.shared.Type.UUID> getIdsList() {
        return java.util.Collections.unmodifiableList(
            instance.getIdsList());
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      @java.lang.Override
      public int getIdsCount() {
        return instance.getIdsCount();
      }/**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.UUID getIds(int index) {
        return instance.getIds(index);
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder setIds(
          int index, net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.setIds(index, value);
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder setIds(
          int index, net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.setIds(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder addIds(net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.addIds(value);
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder addIds(
          int index, net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.addIds(index, value);
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder addIds(
          net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.addIds(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder addIds(
          int index, net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.addIds(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder addAllIds(
          java.lang.Iterable<? extends net.twinte.api.shared.Type.UUID> values) {
        copyOnWrite();
        instance.addAllIds(values);
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder clearIds() {
        copyOnWrite();
        instance.clearIds();
        return this;
      }
      /**
       * <code>repeated .shared.UUID ids = 1 [json_name = "ids"];</code>
       */
      public Builder removeIds(int index) {
        copyOnWrite();
        instance.removeIds(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:announcement.v1.ReadAnnouncementsRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "ids_",
              net.twinte.api.shared.Type.UUID.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:announcement.v1.ReadAnnouncementsRequest)
    private static final net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest DEFAULT_INSTANCE;
    static {
      ReadAnnouncementsRequest defaultInstance = new ReadAnnouncementsRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ReadAnnouncementsRequest.class, defaultInstance);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ReadAnnouncementsRequest> PARSER;

    public static com.google.protobuf.Parser<ReadAnnouncementsRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ReadAnnouncementsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:announcement.v1.ReadAnnouncementsResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code announcement.v1.ReadAnnouncementsResponse}
   */
  public  static final class ReadAnnouncementsResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ReadAnnouncementsResponse, ReadAnnouncementsResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:announcement.v1.ReadAnnouncementsResponse)
      ReadAnnouncementsResponseOrBuilder {
    private ReadAnnouncementsResponse() {
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code announcement.v1.ReadAnnouncementsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:announcement.v1.ReadAnnouncementsResponse)
        net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponseOrBuilder {
      // Construct using net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:announcement.v1.ReadAnnouncementsResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:announcement.v1.ReadAnnouncementsResponse)
    private static final net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse DEFAULT_INSTANCE;
    static {
      ReadAnnouncementsResponse defaultInstance = new ReadAnnouncementsResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ReadAnnouncementsResponse.class, defaultInstance);
    }

    public static net.twinte.api.announcement.v1.Service.ReadAnnouncementsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ReadAnnouncementsResponse> PARSER;

    public static com.google.protobuf.Parser<ReadAnnouncementsResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
