// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: announcement/v1/type.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.announcement.v1;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code announcement.v1.AnnouncementTag}
   */
  public enum AnnouncementTag
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ANNOUNCEMENT_TAG_UNSPECIFIED = 0;</code>
     */
    ANNOUNCEMENT_TAG_UNSPECIFIED(0),
    /**
     * <code>ANNOUNCEMENT_TAG_INFORMATION = 1;</code>
     */
    ANNOUNCEMENT_TAG_INFORMATION(1),
    /**
     * <code>ANNOUNCEMENT_TAG_NOTIFICATION = 2;</code>
     */
    ANNOUNCEMENT_TAG_NOTIFICATION(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ANNOUNCEMENT_TAG_UNSPECIFIED = 0;</code>
     */
    public static final int ANNOUNCEMENT_TAG_UNSPECIFIED_VALUE = 0;
    /**
     * <code>ANNOUNCEMENT_TAG_INFORMATION = 1;</code>
     */
    public static final int ANNOUNCEMENT_TAG_INFORMATION_VALUE = 1;
    /**
     * <code>ANNOUNCEMENT_TAG_NOTIFICATION = 2;</code>
     */
    public static final int ANNOUNCEMENT_TAG_NOTIFICATION_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AnnouncementTag valueOf(int value) {
      return forNumber(value);
    }

    public static AnnouncementTag forNumber(int value) {
      switch (value) {
        case 0: return ANNOUNCEMENT_TAG_UNSPECIFIED;
        case 1: return ANNOUNCEMENT_TAG_INFORMATION;
        case 2: return ANNOUNCEMENT_TAG_NOTIFICATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AnnouncementTag>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AnnouncementTag> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AnnouncementTag>() {
            @java.lang.Override
            public AnnouncementTag findValueByNumber(int number) {
              return AnnouncementTag.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return AnnouncementTagVerifier.INSTANCE;
    }

    private static final class AnnouncementTagVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new AnnouncementTagVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return AnnouncementTag.forNumber(number) != null;
            }
          };

    private final int value;

    private AnnouncementTag(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:announcement.v1.AnnouncementTag)
  }

  public interface AnnouncementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:announcement.v1.Announcement)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    net.twinte.api.shared.Type.UUID getId();

    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @return A list containing the tags.
     */
    java.util.List<net.twinte.api.announcement.v1.Type.AnnouncementTag> getTagsList();
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @return The count of tags.
     */
    int getTagsCount();
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    net.twinte.api.announcement.v1.Type.AnnouncementTag getTags(int index);
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @return A list containing the enum numeric values on the wire for tags.
     */
    java.util.List<java.lang.Integer>
    getTagsValueList();
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of tags at the given index.
     */
    int getTagsValue(int index);

    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string content = 4 [json_name = "content"];</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 4 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     * @return Whether the publishedAt field is set.
     */
    boolean hasPublishedAt();
    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     * @return The publishedAt.
     */
    net.twinte.api.shared.Type.RFC3339DateTime getPublishedAt();

    /**
     * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
     * @return Whether the isRead field is set.
     */
    boolean hasIsRead();
    /**
     * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
     * @return The isRead.
     */
    boolean getIsRead();
  }
  /**
   * <pre>
   * If authenticated, is_read is present.
   * </pre>
   *
   * Protobuf type {@code announcement.v1.Announcement}
   */
  public  static final class Announcement extends
      com.google.protobuf.GeneratedMessageLite<
          Announcement, Announcement.Builder> implements
      // @@protoc_insertion_point(message_implements:announcement.v1.Announcement)
      AnnouncementOrBuilder {
    private Announcement() {
      tags_ = emptyIntList();
      title_ = "";
      content_ = "";
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private net.twinte.api.shared.Type.UUID id_;
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.UUID getId() {
      return id_ == null ? net.twinte.api.shared.Type.UUID.getDefaultInstance() : id_;
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setId(net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      id_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeId(net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      if (id_ != null &&
          id_ != net.twinte.api.shared.Type.UUID.getDefaultInstance()) {
        id_ =
          net.twinte.api.shared.Type.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
      } else {
        id_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    private void clearId() {
      id_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int TAGS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList tags_;
    private static final com.google.protobuf.Internal.IntListAdapter.IntConverter<
        net.twinte.api.announcement.v1.Type.AnnouncementTag> tags_converter_ =
            new com.google.protobuf.Internal.IntListAdapter.IntConverter<
                net.twinte.api.announcement.v1.Type.AnnouncementTag>() {
              @java.lang.Override
              public net.twinte.api.announcement.v1.Type.AnnouncementTag convert(int from) {
                net.twinte.api.announcement.v1.Type.AnnouncementTag result = net.twinte.api.announcement.v1.Type.AnnouncementTag.forNumber(from);
                return result == null ? net.twinte.api.announcement.v1.Type.AnnouncementTag.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @return A list containing the tags.
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.announcement.v1.Type.AnnouncementTag> getTagsList() {
      return new com.google.protobuf.Internal.IntListAdapter<
          net.twinte.api.announcement.v1.Type.AnnouncementTag>(tags_, tags_converter_);
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @return The count of tags.
     */
    @java.lang.Override
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    @java.lang.Override
    public net.twinte.api.announcement.v1.Type.AnnouncementTag getTags(int index) {
      net.twinte.api.announcement.v1.Type.AnnouncementTag result = net.twinte.api.announcement.v1.Type.AnnouncementTag.forNumber(tags_.getInt(index));
      return result == null ? net.twinte.api.announcement.v1.Type.AnnouncementTag.UNRECOGNIZED : result;
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @return A list containing the enum numeric values on the wire for tags.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getTagsValueList() {
      return tags_;
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of tags at the given index.
     */
    @java.lang.Override
    public int getTagsValue(int index) {
      return tags_.getInt(index);
    }
    private int tagsMemoizedSerializedSize;
    private void ensureTagsIsMutable() {
      com.google.protobuf.Internal.IntList tmp = tags_;
      if (!tmp.isModifiable()) {
        tags_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
      }
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setTags(
        int index, net.twinte.api.announcement.v1.Type.AnnouncementTag value) {
      value.getClass();  // minimal bytecode null check
      ensureTagsIsMutable();
      tags_.setInt(index, value.getNumber());
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param value The tags to add.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addTags(net.twinte.api.announcement.v1.Type.AnnouncementTag value) {
      value.getClass();  // minimal bytecode null check
      ensureTagsIsMutable();
      tags_.addInt(value.getNumber());
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param values The tags to add.
     */
    private void addAllTags(
        java.lang.Iterable<? extends net.twinte.api.announcement.v1.Type.AnnouncementTag> values) {
      ensureTagsIsMutable();
      for (net.twinte.api.announcement.v1.Type.AnnouncementTag value : values) {
        tags_.addInt(value.getNumber());
      }
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     */
    private void clearTags() {
      tags_ = emptyIntList();
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param value The enum numeric value on the wire for tags to set.
     */
    private void setTagsValue(
        int index, int value) {
      ensureTagsIsMutable();
      tags_.setInt(index, value);
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param value The enum numeric value on the wire for tags to add.
     */
    private void addTagsValue(int value) {
      ensureTagsIsMutable();
      tags_.addInt(value);
    }
    /**
     * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
     * @param values The enum numeric values on the wire for tags to add.
     */
    private void addAllTagsValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureTagsIsMutable();
      for (int value : values) {
        tags_.addInt(value);
      }
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.String title_;
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @param value The title to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setTitle(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      title_ = value;
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     */
    private void clearTitle() {

      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>string title = 3 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      title_ = value.toStringUtf8();

    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private java.lang.String content_;
    /**
     * <code>string content = 4 [json_name = "content"];</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>string content = 4 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>string content = 4 [json_name = "content"];</code>
     * @param value The content to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setContent(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      content_ = value;
    }
    /**
     * <code>string content = 4 [json_name = "content"];</code>
     */
    private void clearContent() {

      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>string content = 4 [json_name = "content"];</code>
     * @param value The bytes for content to set.
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      content_ = value.toStringUtf8();

    }

    public static final int PUBLISHED_AT_FIELD_NUMBER = 5;
    private net.twinte.api.shared.Type.RFC3339DateTime publishedAt_;
    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     */
    @java.lang.Override
    public boolean hasPublishedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.RFC3339DateTime getPublishedAt() {
      return publishedAt_ == null ? net.twinte.api.shared.Type.RFC3339DateTime.getDefaultInstance() : publishedAt_;
    }
    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setPublishedAt(net.twinte.api.shared.Type.RFC3339DateTime value) {
      value.getClass();  // minimal bytecode null check
      publishedAt_ = value;
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergePublishedAt(net.twinte.api.shared.Type.RFC3339DateTime value) {
      value.getClass();  // minimal bytecode null check
      if (publishedAt_ != null &&
          publishedAt_ != net.twinte.api.shared.Type.RFC3339DateTime.getDefaultInstance()) {
        publishedAt_ =
          net.twinte.api.shared.Type.RFC3339DateTime.newBuilder(publishedAt_).mergeFrom(value).buildPartial();
      } else {
        publishedAt_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
     */
    private void clearPublishedAt() {
      publishedAt_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int IS_READ_FIELD_NUMBER = 6;
    private boolean isRead_;
    /**
     * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
     * @return Whether the isRead field is set.
     */
    @java.lang.Override
    public boolean hasIsRead() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
     * @return The isRead.
     */
    @java.lang.Override
    public boolean getIsRead() {
      return isRead_;
    }
    /**
     * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
     * @param value The isRead to set.
     */
    private void setIsRead(boolean value) {
      bitField0_ |= 0x00000004;
      isRead_ = value;
    }
    /**
     * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
     */
    private void clearIsRead() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isRead_ = false;
    }

    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.announcement.v1.Type.Announcement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.announcement.v1.Type.Announcement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.announcement.v1.Type.Announcement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.announcement.v1.Type.Announcement prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * If authenticated, is_read is present.
     * </pre>
     *
     * Protobuf type {@code announcement.v1.Announcement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.announcement.v1.Type.Announcement, Builder> implements
        // @@protoc_insertion_point(builder_implements:announcement.v1.Announcement)
        net.twinte.api.announcement.v1.Type.AnnouncementOrBuilder {
      // Construct using net.twinte.api.announcement.v1.Type.Announcement.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      @java.lang.Override
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.UUID getId() {
        return instance.getId();
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder setId(net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.setId(value);
        return this;
        }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder setId(
          net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.setId(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder mergeId(net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.mergeId(value);
        return this;
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder clearId() {  copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @return A list containing the tags.
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.announcement.v1.Type.AnnouncementTag> getTagsList() {
        return instance.getTagsList();
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @return The count of tags.
       */
      @java.lang.Override
      public int getTagsCount() {
        return instance.getTagsCount();
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param index The index of the element to return.
       * @return The tags at the given index.
       */
      @java.lang.Override
      public net.twinte.api.announcement.v1.Type.AnnouncementTag getTags(int index) {
        return instance.getTags(index);
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param index The index to set the value at.
       * @param value The tags to set.
       * @return This builder for chaining.
       */
      public Builder setTags(
          int index, net.twinte.api.announcement.v1.Type.AnnouncementTag value) {
        copyOnWrite();
        instance.setTags(index, value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param value The tags to add.
       * @return This builder for chaining.
       */
      public Builder addTags(net.twinte.api.announcement.v1.Type.AnnouncementTag value) {
        copyOnWrite();
        instance.addTags(value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param values The tags to add.
       * @return This builder for chaining.
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends net.twinte.api.announcement.v1.Type.AnnouncementTag> values) {
        copyOnWrite();
        instance.addAllTags(values);  return this;
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTags() {
        copyOnWrite();
        instance.clearTags();
        return this;
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @return A list containing the enum numeric values on the wire for tags.
       */
      @java.lang.Override
      public java.util.List<java.lang.Integer>
      getTagsValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getTagsValueList());
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of tags at the given index.
       */
      @java.lang.Override
      public int getTagsValue(int index) {
        return instance.getTagsValue(index);
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for tags to set.
       * @return This builder for chaining.
       */
      public Builder setTagsValue(
          int index, int value) {
        copyOnWrite();
        instance.setTagsValue(index, value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param value The enum numeric value on the wire for tags to add.
       * @return This builder for chaining.
       */
      public Builder addTagsValue(int value) {
        copyOnWrite();
        instance.addTagsValue(value);
        return this;
      }
      /**
       * <code>repeated .announcement.v1.AnnouncementTag tags = 2 [json_name = "tags"];</code>
       * @param values The enum numeric values on the wire for tags to add.
       * @return This builder for chaining.
       */
      public Builder addAllTagsValue(
          java.lang.Iterable<java.lang.Integer> values) {
        copyOnWrite();
        instance.addAllTagsValue(values);
        return this;
      }

      /**
       * <code>string title = 3 [json_name = "title"];</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>string title = 3 [json_name = "title"];</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>string title = 3 [json_name = "title"];</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>string title = 3 [json_name = "title"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>string title = 3 [json_name = "title"];</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>string content = 4 [json_name = "content"];</code>
       * @return The content.
       */
      @java.lang.Override
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>string content = 4 [json_name = "content"];</code>
       * @return The bytes for content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>string content = 4 [json_name = "content"];</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>string content = 4 [json_name = "content"];</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>string content = 4 [json_name = "content"];</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
       */
      @java.lang.Override
      public boolean hasPublishedAt() {
        return instance.hasPublishedAt();
      }
      /**
       * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.RFC3339DateTime getPublishedAt() {
        return instance.getPublishedAt();
      }
      /**
       * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
       */
      public Builder setPublishedAt(net.twinte.api.shared.Type.RFC3339DateTime value) {
        copyOnWrite();
        instance.setPublishedAt(value);
        return this;
        }
      /**
       * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
       */
      public Builder setPublishedAt(
          net.twinte.api.shared.Type.RFC3339DateTime.Builder builderForValue) {
        copyOnWrite();
        instance.setPublishedAt(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
       */
      public Builder mergePublishedAt(net.twinte.api.shared.Type.RFC3339DateTime value) {
        copyOnWrite();
        instance.mergePublishedAt(value);
        return this;
      }
      /**
       * <code>.shared.RFC3339DateTime published_at = 5 [json_name = "publishedAt"];</code>
       */
      public Builder clearPublishedAt() {  copyOnWrite();
        instance.clearPublishedAt();
        return this;
      }

      /**
       * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
       * @return Whether the isRead field is set.
       */
      @java.lang.Override
      public boolean hasIsRead() {
        return instance.hasIsRead();
      }
      /**
       * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
       * @return The isRead.
       */
      @java.lang.Override
      public boolean getIsRead() {
        return instance.getIsRead();
      }
      /**
       * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
       * @param value The isRead to set.
       * @return This builder for chaining.
       */
      public Builder setIsRead(boolean value) {
        copyOnWrite();
        instance.setIsRead(value);
        return this;
      }
      /**
       * <code>optional bool is_read = 6 [json_name = "isRead"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIsRead() {
        copyOnWrite();
        instance.clearIsRead();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:announcement.v1.Announcement)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.announcement.v1.Type.Announcement();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "id_",
              "tags_",
              "title_",
              "content_",
              "publishedAt_",
              "isRead_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u1009\u0000\u0002" +
                ",\u0003\u0208\u0004\u0208\u0005\u1009\u0001\u0006\u1007\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.announcement.v1.Type.Announcement> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.announcement.v1.Type.Announcement.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.announcement.v1.Type.Announcement>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:announcement.v1.Announcement)
    private static final net.twinte.api.announcement.v1.Type.Announcement DEFAULT_INSTANCE;
    static {
      Announcement defaultInstance = new Announcement();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Announcement.class, defaultInstance);
    }

    public static net.twinte.api.announcement.v1.Type.Announcement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Announcement> PARSER;

    public static com.google.protobuf.Parser<Announcement> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
