// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: schoolcalendar/v1/service.proto
//
package net.twinte.api.schoolcalendar.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The following error codes are not stated explicitly in the each rpc, but may be returned.
 *    - shared.InvalidArgument
 *    - shared.Unauthenticated
 *    - shared.Unauthorized
 */
public interface SchoolCalendarServiceClientInterface {
  public suspend fun listEventsByDate(request: Service.ListEventsByDateRequest, headers: Headers = emptyMap()): ResponseMessage<Service.ListEventsByDateResponse>

  public suspend fun getModuleByDate(request: Service.GetModuleByDateRequest, headers: Headers = emptyMap()): ResponseMessage<Service.GetModuleByDateResponse>
}
