// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: schoolcalendar/v1/service.proto
//
package net.twinte.api.schoolcalendar.v1

import com.connectrpc.Headers
import com.connectrpc.Idempotency
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  The following error codes are not stated explicitly in the each rpc, but may be returned.
 *    - shared.InvalidArgument
 *    - shared.Unauthenticated
 *    - shared.Unauthorized
 */
public class SchoolCalendarServiceClient(
  private val client: ProtocolClientInterface,
) : SchoolCalendarServiceClientInterface {
  override suspend fun listEventsByDate(request: Service.ListEventsByDateRequest, headers: Headers): ResponseMessage<Service.ListEventsByDateResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "schoolcalendar.v1.SchoolCalendarService/ListEventsByDate",
      net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest::class,
      net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.NO_SIDE_EFFECTS,
    ),
  )


  override suspend fun getModuleByDate(request: Service.GetModuleByDateRequest, headers: Headers): ResponseMessage<Service.GetModuleByDateResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "schoolcalendar.v1.SchoolCalendarService/GetModuleByDate",
      net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest::class,
      net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.NO_SIDE_EFFECTS,
    ),
  )

}
