// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: schoolcalendar/v1/service.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.schoolcalendar.v1;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ListEventsByDateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schoolcalendar.v1.ListEventsByDateRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     * @return The date.
     */
    net.twinte.api.shared.Type.RFC3339FullDate getDate();
  }
  /**
   * Protobuf type {@code schoolcalendar.v1.ListEventsByDateRequest}
   */
  public  static final class ListEventsByDateRequest extends
      com.google.protobuf.GeneratedMessageLite<
          ListEventsByDateRequest, ListEventsByDateRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:schoolcalendar.v1.ListEventsByDateRequest)
      ListEventsByDateRequestOrBuilder {
    private ListEventsByDateRequest() {
    }
    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private net.twinte.api.shared.Type.RFC3339FullDate date_;
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
      return date_ == null ? net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance() : date_;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      date_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      if (date_ != null &&
          date_ != net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance()) {
        date_ =
          net.twinte.api.shared.Type.RFC3339FullDate.newBuilder(date_).mergeFrom(value).buildPartial();
      } else {
        date_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    private void clearDate() {
      date_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code schoolcalendar.v1.ListEventsByDateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:schoolcalendar.v1.ListEventsByDateRequest)
        net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequestOrBuilder {
      // Construct using net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      @java.lang.Override
      public boolean hasDate() {
        return instance.hasDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
        return instance.getDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.setDate(value);
        return this;
        }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder setDate(
          net.twinte.api.shared.Type.RFC3339FullDate.Builder builderForValue) {
        copyOnWrite();
        instance.setDate(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.mergeDate(value);
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder clearDate() {  copyOnWrite();
        instance.clearDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schoolcalendar.v1.ListEventsByDateRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "date_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:schoolcalendar.v1.ListEventsByDateRequest)
    private static final net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest DEFAULT_INSTANCE;
    static {
      ListEventsByDateRequest defaultInstance = new ListEventsByDateRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ListEventsByDateRequest.class, defaultInstance);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ListEventsByDateRequest> PARSER;

    public static com.google.protobuf.Parser<ListEventsByDateRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ListEventsByDateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schoolcalendar.v1.ListEventsByDateResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    java.util.List<net.twinte.api.schoolcalendar.v1.Type.Event> 
        getEventsList();
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    net.twinte.api.schoolcalendar.v1.Type.Event getEvents(int index);
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    int getEventsCount();
  }
  /**
   * Protobuf type {@code schoolcalendar.v1.ListEventsByDateResponse}
   */
  public  static final class ListEventsByDateResponse extends
      com.google.protobuf.GeneratedMessageLite<
          ListEventsByDateResponse, ListEventsByDateResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:schoolcalendar.v1.ListEventsByDateResponse)
      ListEventsByDateResponseOrBuilder {
    private ListEventsByDateResponse() {
      events_ = emptyProtobufList();
    }
    public static final int EVENTS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.schoolcalendar.v1.Type.Event> events_;
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.schoolcalendar.v1.Type.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    public java.util.List<? extends net.twinte.api.schoolcalendar.v1.Type.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.Override
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.Override
    public net.twinte.api.schoolcalendar.v1.Type.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    public net.twinte.api.schoolcalendar.v1.Type.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }
    private void ensureEventsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.schoolcalendar.v1.Type.Event> tmp = events_;
      if (!tmp.isModifiable()) {
        events_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setEvents(
        int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
      value.getClass();  // minimal bytecode null check
      ensureEventsIsMutable();
      events_.set(index, value);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addEvents(net.twinte.api.schoolcalendar.v1.Type.Event value) {
      value.getClass();  // minimal bytecode null check
      ensureEventsIsMutable();
      events_.add(value);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addEvents(
        int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
      value.getClass();  // minimal bytecode null check
      ensureEventsIsMutable();
      events_.add(index, value);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    private void addAllEvents(
        java.lang.Iterable<? extends net.twinte.api.schoolcalendar.v1.Type.Event> values) {
      ensureEventsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, events_);
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    private void clearEvents() {
      events_ = emptyProtobufList();
    }
    /**
     * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
     */
    private void removeEvents(int index) {
      ensureEventsIsMutable();
      events_.remove(index);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code schoolcalendar.v1.ListEventsByDateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:schoolcalendar.v1.ListEventsByDateResponse)
        net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponseOrBuilder {
      // Construct using net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.schoolcalendar.v1.Type.Event> getEventsList() {
        return java.util.Collections.unmodifiableList(
            instance.getEventsList());
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      @java.lang.Override
      public int getEventsCount() {
        return instance.getEventsCount();
      }/**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      @java.lang.Override
      public net.twinte.api.schoolcalendar.v1.Type.Event getEvents(int index) {
        return instance.getEvents(index);
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder setEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
        copyOnWrite();
        instance.setEvents(index, value);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder setEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event.Builder builderForValue) {
        copyOnWrite();
        instance.setEvents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(net.twinte.api.schoolcalendar.v1.Type.Event value) {
        copyOnWrite();
        instance.addEvents(value);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event value) {
        copyOnWrite();
        instance.addEvents(index, value);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(
          net.twinte.api.schoolcalendar.v1.Type.Event.Builder builderForValue) {
        copyOnWrite();
        instance.addEvents(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addEvents(
          int index, net.twinte.api.schoolcalendar.v1.Type.Event.Builder builderForValue) {
        copyOnWrite();
        instance.addEvents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends net.twinte.api.schoolcalendar.v1.Type.Event> values) {
        copyOnWrite();
        instance.addAllEvents(values);
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder clearEvents() {
        copyOnWrite();
        instance.clearEvents();
        return this;
      }
      /**
       * <code>repeated .schoolcalendar.v1.Event events = 1 [json_name = "events"];</code>
       */
      public Builder removeEvents(int index) {
        copyOnWrite();
        instance.removeEvents(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schoolcalendar.v1.ListEventsByDateResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "events_",
              net.twinte.api.schoolcalendar.v1.Type.Event.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:schoolcalendar.v1.ListEventsByDateResponse)
    private static final net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse DEFAULT_INSTANCE;
    static {
      ListEventsByDateResponse defaultInstance = new ListEventsByDateResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ListEventsByDateResponse.class, defaultInstance);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.ListEventsByDateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ListEventsByDateResponse> PARSER;

    public static com.google.protobuf.Parser<ListEventsByDateResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetModuleByDateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schoolcalendar.v1.GetModuleByDateRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     * @return The date.
     */
    net.twinte.api.shared.Type.RFC3339FullDate getDate();
  }
  /**
   * Protobuf type {@code schoolcalendar.v1.GetModuleByDateRequest}
   */
  public  static final class GetModuleByDateRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetModuleByDateRequest, GetModuleByDateRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:schoolcalendar.v1.GetModuleByDateRequest)
      GetModuleByDateRequestOrBuilder {
    private GetModuleByDateRequest() {
    }
    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private net.twinte.api.shared.Type.RFC3339FullDate date_;
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
      return date_ == null ? net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance() : date_;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      date_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      if (date_ != null &&
          date_ != net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance()) {
        date_ =
          net.twinte.api.shared.Type.RFC3339FullDate.newBuilder(date_).mergeFrom(value).buildPartial();
      } else {
        date_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
     */
    private void clearDate() {
      date_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code schoolcalendar.v1.GetModuleByDateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:schoolcalendar.v1.GetModuleByDateRequest)
        net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequestOrBuilder {
      // Construct using net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      @java.lang.Override
      public boolean hasDate() {
        return instance.hasDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
        return instance.getDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.setDate(value);
        return this;
        }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder setDate(
          net.twinte.api.shared.Type.RFC3339FullDate.Builder builderForValue) {
        copyOnWrite();
        instance.setDate(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.mergeDate(value);
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 1 [json_name = "date"];</code>
       */
      public Builder clearDate() {  copyOnWrite();
        instance.clearDate();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schoolcalendar.v1.GetModuleByDateRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "date_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:schoolcalendar.v1.GetModuleByDateRequest)
    private static final net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest DEFAULT_INSTANCE;
    static {
      GetModuleByDateRequest defaultInstance = new GetModuleByDateRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetModuleByDateRequest.class, defaultInstance);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetModuleByDateRequest> PARSER;

    public static com.google.protobuf.Parser<GetModuleByDateRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetModuleByDateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schoolcalendar.v1.GetModuleByDateResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     * @return The enum numeric value on the wire for module.
     */
    int getModuleValue();
    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     * @return The module.
     */
    net.twinte.api.schoolcalendar.v1.Type.Module getModule();
  }
  /**
   * Protobuf type {@code schoolcalendar.v1.GetModuleByDateResponse}
   */
  public  static final class GetModuleByDateResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetModuleByDateResponse, GetModuleByDateResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:schoolcalendar.v1.GetModuleByDateResponse)
      GetModuleByDateResponseOrBuilder {
    private GetModuleByDateResponse() {
    }
    public static final int MODULE_FIELD_NUMBER = 1;
    private int module_;
    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     * @return The enum numeric value on the wire for module.
     */
    @java.lang.Override
    public int getModuleValue() {
      return module_;
    }
    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     * @return The module.
     */
    @java.lang.Override
    public net.twinte.api.schoolcalendar.v1.Type.Module getModule() {
      net.twinte.api.schoolcalendar.v1.Type.Module result = net.twinte.api.schoolcalendar.v1.Type.Module.forNumber(module_);
      return result == null ? net.twinte.api.schoolcalendar.v1.Type.Module.UNRECOGNIZED : result;
    }
    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     * @param value The enum numeric value on the wire for module to set.
     */
    private void setModuleValue(int value) {
        module_ = value;
    }
    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     * @param value The module to set.
     */
    private void setModule(net.twinte.api.schoolcalendar.v1.Type.Module value) {
      module_ = value.getNumber();

    }
    /**
     * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
     */
    private void clearModule() {

      module_ = 0;
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code schoolcalendar.v1.GetModuleByDateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:schoolcalendar.v1.GetModuleByDateResponse)
        net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponseOrBuilder {
      // Construct using net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
       * @return The enum numeric value on the wire for module.
       */
      @java.lang.Override
      public int getModuleValue() {
        return instance.getModuleValue();
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
       * @param value The module to set.
       * @return This builder for chaining.
       */
      public Builder setModuleValue(int value) {
        copyOnWrite();
        instance.setModuleValue(value);
        return this;
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
       * @return The module.
       */
      @java.lang.Override
      public net.twinte.api.schoolcalendar.v1.Type.Module getModule() {
        return instance.getModule();
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
       * @param value The enum numeric value on the wire for module to set.
       * @return This builder for chaining.
       */
      public Builder setModule(net.twinte.api.schoolcalendar.v1.Type.Module value) {
        copyOnWrite();
        instance.setModule(value);
        return this;
      }
      /**
       * <code>.schoolcalendar.v1.Module module = 1 [json_name = "module"];</code>
       * @return This builder for chaining.
       */
      public Builder clearModule() {
        copyOnWrite();
        instance.clearModule();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schoolcalendar.v1.GetModuleByDateResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "module_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:schoolcalendar.v1.GetModuleByDateResponse)
    private static final net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse DEFAULT_INSTANCE;
    static {
      GetModuleByDateResponse defaultInstance = new GetModuleByDateResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetModuleByDateResponse.class, defaultInstance);
    }

    public static net.twinte.api.schoolcalendar.v1.Service.GetModuleByDateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetModuleByDateResponse> PARSER;

    public static com.google.protobuf.Parser<GetModuleByDateResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
