// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: schoolcalendar/v1/type.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.schoolcalendar.v1;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code schoolcalendar.v1.EventType}
   */
  public enum EventType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>EVENT_TYPE_UNSPECIFIED = 0;</code>
     */
    EVENT_TYPE_UNSPECIFIED(0),
    /**
     * <code>EVENT_TYPE_HOLIDAY = 1;</code>
     */
    EVENT_TYPE_HOLIDAY(1),
    /**
     * <code>EVENT_TYPE_PUBLIC_HOLIDAY = 2;</code>
     */
    EVENT_TYPE_PUBLIC_HOLIDAY(2),
    /**
     * <code>EVENT_TYPE_EXAM = 3;</code>
     */
    EVENT_TYPE_EXAM(3),
    /**
     * <code>EVENT_TYPE_SUBSTITUTE_DAY = 4;</code>
     */
    EVENT_TYPE_SUBSTITUTE_DAY(4),
    /**
     * <code>EVENT_TYPE_OTHER = 5;</code>
     */
    EVENT_TYPE_OTHER(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EVENT_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int EVENT_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>EVENT_TYPE_HOLIDAY = 1;</code>
     */
    public static final int EVENT_TYPE_HOLIDAY_VALUE = 1;
    /**
     * <code>EVENT_TYPE_PUBLIC_HOLIDAY = 2;</code>
     */
    public static final int EVENT_TYPE_PUBLIC_HOLIDAY_VALUE = 2;
    /**
     * <code>EVENT_TYPE_EXAM = 3;</code>
     */
    public static final int EVENT_TYPE_EXAM_VALUE = 3;
    /**
     * <code>EVENT_TYPE_SUBSTITUTE_DAY = 4;</code>
     */
    public static final int EVENT_TYPE_SUBSTITUTE_DAY_VALUE = 4;
    /**
     * <code>EVENT_TYPE_OTHER = 5;</code>
     */
    public static final int EVENT_TYPE_OTHER_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return EVENT_TYPE_UNSPECIFIED;
        case 1: return EVENT_TYPE_HOLIDAY;
        case 2: return EVENT_TYPE_PUBLIC_HOLIDAY;
        case 3: return EVENT_TYPE_EXAM;
        case 4: return EVENT_TYPE_SUBSTITUTE_DAY;
        case 5: return EVENT_TYPE_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            @java.lang.Override
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return EventTypeVerifier.INSTANCE;
    }

    private static final class EventTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new EventTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return EventType.forNumber(number) != null;
            }
          };

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:schoolcalendar.v1.EventType)
  }

  /**
   * Protobuf enum {@code schoolcalendar.v1.Module}
   */
  public enum Module
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MODULE_UNSPECIFIED = 0;</code>
     */
    MODULE_UNSPECIFIED(0),
    /**
     * <code>MODULE_SPRING_A = 1;</code>
     */
    MODULE_SPRING_A(1),
    /**
     * <code>MODULE_SPRING_B = 2;</code>
     */
    MODULE_SPRING_B(2),
    /**
     * <code>MODULE_SPRING_C = 3;</code>
     */
    MODULE_SPRING_C(3),
    /**
     * <code>MODULE_SUMMER_VACATION = 4;</code>
     */
    MODULE_SUMMER_VACATION(4),
    /**
     * <code>MODULE_FALL_A = 5;</code>
     */
    MODULE_FALL_A(5),
    /**
     * <code>MODULE_FALL_B = 6;</code>
     */
    MODULE_FALL_B(6),
    /**
     * <code>MODULE_WINTER_VACATION = 7;</code>
     */
    MODULE_WINTER_VACATION(7),
    /**
     * <code>MODULE_FALL_C = 8;</code>
     */
    MODULE_FALL_C(8),
    /**
     * <code>MODULE_SPRING_VACATION = 9;</code>
     */
    MODULE_SPRING_VACATION(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MODULE_UNSPECIFIED = 0;</code>
     */
    public static final int MODULE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>MODULE_SPRING_A = 1;</code>
     */
    public static final int MODULE_SPRING_A_VALUE = 1;
    /**
     * <code>MODULE_SPRING_B = 2;</code>
     */
    public static final int MODULE_SPRING_B_VALUE = 2;
    /**
     * <code>MODULE_SPRING_C = 3;</code>
     */
    public static final int MODULE_SPRING_C_VALUE = 3;
    /**
     * <code>MODULE_SUMMER_VACATION = 4;</code>
     */
    public static final int MODULE_SUMMER_VACATION_VALUE = 4;
    /**
     * <code>MODULE_FALL_A = 5;</code>
     */
    public static final int MODULE_FALL_A_VALUE = 5;
    /**
     * <code>MODULE_FALL_B = 6;</code>
     */
    public static final int MODULE_FALL_B_VALUE = 6;
    /**
     * <code>MODULE_WINTER_VACATION = 7;</code>
     */
    public static final int MODULE_WINTER_VACATION_VALUE = 7;
    /**
     * <code>MODULE_FALL_C = 8;</code>
     */
    public static final int MODULE_FALL_C_VALUE = 8;
    /**
     * <code>MODULE_SPRING_VACATION = 9;</code>
     */
    public static final int MODULE_SPRING_VACATION_VALUE = 9;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Module valueOf(int value) {
      return forNumber(value);
    }

    public static Module forNumber(int value) {
      switch (value) {
        case 0: return MODULE_UNSPECIFIED;
        case 1: return MODULE_SPRING_A;
        case 2: return MODULE_SPRING_B;
        case 3: return MODULE_SPRING_C;
        case 4: return MODULE_SUMMER_VACATION;
        case 5: return MODULE_FALL_A;
        case 6: return MODULE_FALL_B;
        case 7: return MODULE_WINTER_VACATION;
        case 8: return MODULE_FALL_C;
        case 9: return MODULE_SPRING_VACATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Module>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Module> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Module>() {
            @java.lang.Override
            public Module findValueByNumber(int number) {
              return Module.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ModuleVerifier.INSTANCE;
    }

    private static final class ModuleVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new ModuleVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Module.forNumber(number) != null;
            }
          };

    private final int value;

    private Module(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:schoolcalendar.v1.Module)
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schoolcalendar.v1.Event)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     * @return The type.
     */
    net.twinte.api.schoolcalendar.v1.Type.EventType getType();

    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     * @return The date.
     */
    net.twinte.api.shared.Type.RFC3339FullDate getDate();

    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @return Whether the changeTo field is set.
     */
    boolean hasChangeTo();
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @return The enum numeric value on the wire for changeTo.
     */
    int getChangeToValue();
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @return The changeTo.
     */
    net.twinte.api.shared.Type.Weekday getChangeTo();
  }
  /**
   * Protobuf type {@code schoolcalendar.v1.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageLite<
          Event, Event.Builder> implements
      // @@protoc_insertion_point(message_implements:schoolcalendar.v1.Event)
      EventOrBuilder {
    private Event() {
      description_ = "";
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     */
    private void clearId() {

      id_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public net.twinte.api.schoolcalendar.v1.Type.EventType getType() {
      net.twinte.api.schoolcalendar.v1.Type.EventType result = net.twinte.api.schoolcalendar.v1.Type.EventType.forNumber(type_);
      return result == null ? net.twinte.api.schoolcalendar.v1.Type.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     * @param value The type to set.
     */
    private void setType(net.twinte.api.schoolcalendar.v1.Type.EventType value) {
      type_ = value.getNumber();

    }
    /**
     * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private net.twinte.api.shared.Type.RFC3339FullDate date_;
    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
      return date_ == null ? net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance() : date_;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      date_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
      value.getClass();  // minimal bytecode null check
      if (date_ != null &&
          date_ != net.twinte.api.shared.Type.RFC3339FullDate.getDefaultInstance()) {
        date_ =
          net.twinte.api.shared.Type.RFC3339FullDate.newBuilder(date_).mergeFrom(value).buildPartial();
      } else {
        date_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
     */
    private void clearDate() {
      date_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private java.lang.String description_;
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return description_;
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(description_);
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @param value The description to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setDescription(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      description_ = value;
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     */
    private void clearDescription() {

      description_ = getDefaultInstance().getDescription();
    }
    /**
     * <code>string description = 4 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     */
    private void setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      description_ = value.toStringUtf8();

    }

    public static final int CHANGE_TO_FIELD_NUMBER = 5;
    private int changeTo_;
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @return Whether the changeTo field is set.
     */
    @java.lang.Override
    public boolean hasChangeTo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @return The enum numeric value on the wire for changeTo.
     */
    @java.lang.Override
    public int getChangeToValue() {
      return changeTo_;
    }
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @return The changeTo.
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.Weekday getChangeTo() {
      net.twinte.api.shared.Type.Weekday result = net.twinte.api.shared.Type.Weekday.forNumber(changeTo_);
      return result == null ? net.twinte.api.shared.Type.Weekday.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @param value The enum numeric value on the wire for changeTo to set.
     */
    private void setChangeToValue(int value) {
      bitField0_ |= 0x00000002;  changeTo_ = value;
    }
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     * @param value The changeTo to set.
     */
    private void setChangeTo(net.twinte.api.shared.Type.Weekday value) {
      changeTo_ = value.getNumber();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
     */
    private void clearChangeTo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      changeTo_ = 0;
    }

    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.schoolcalendar.v1.Type.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.schoolcalendar.v1.Type.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.schoolcalendar.v1.Type.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.schoolcalendar.v1.Type.Event prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code schoolcalendar.v1.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.schoolcalendar.v1.Type.Event, Builder> implements
        // @@protoc_insertion_point(builder_implements:schoolcalendar.v1.Event)
        net.twinte.api.schoolcalendar.v1.Type.EventOrBuilder {
      // Construct using net.twinte.api.schoolcalendar.v1.Type.Event.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
       * @return The type.
       */
      @java.lang.Override
      public net.twinte.api.schoolcalendar.v1.Type.EventType getType() {
        return instance.getType();
      }
      /**
       * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(net.twinte.api.schoolcalendar.v1.Type.EventType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.schoolcalendar.v1.EventType type = 2 [json_name = "type"];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
       */
      @java.lang.Override
      public boolean hasDate() {
        return instance.hasDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.RFC3339FullDate getDate() {
        return instance.getDate();
      }
      /**
       * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
       */
      public Builder setDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.setDate(value);
        return this;
        }
      /**
       * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
       */
      public Builder setDate(
          net.twinte.api.shared.Type.RFC3339FullDate.Builder builderForValue) {
        copyOnWrite();
        instance.setDate(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
       */
      public Builder mergeDate(net.twinte.api.shared.Type.RFC3339FullDate value) {
        copyOnWrite();
        instance.mergeDate(value);
        return this;
      }
      /**
       * <code>.shared.RFC3339FullDate date = 3 [json_name = "date"];</code>
       */
      public Builder clearDate() {  copyOnWrite();
        instance.clearDate();
        return this;
      }

      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @return The description.
       */
      @java.lang.Override
      public java.lang.String getDescription() {
        return instance.getDescription();
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @return The bytes for description.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        return instance.getDescriptionBytes();
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        copyOnWrite();
        instance.clearDescription();
        return this;
      }
      /**
       * <code>string description = 4 [json_name = "description"];</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescriptionBytes(value);
        return this;
      }

      /**
       * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
       * @return Whether the changeTo field is set.
       */
      @java.lang.Override
      public boolean hasChangeTo() {
        return instance.hasChangeTo();
      }
      /**
       * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
       * @return The enum numeric value on the wire for changeTo.
       */
      @java.lang.Override
      public int getChangeToValue() {
        return instance.getChangeToValue();
      }
      /**
       * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
       * @param value The changeTo to set.
       * @return This builder for chaining.
       */
      public Builder setChangeToValue(int value) {
        copyOnWrite();
        instance.setChangeToValue(value);
        return this;
      }
      /**
       * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
       * @return The changeTo.
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.Weekday getChangeTo() {
        return instance.getChangeTo();
      }
      /**
       * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
       * @param value The enum numeric value on the wire for changeTo to set.
       * @return This builder for chaining.
       */
      public Builder setChangeTo(net.twinte.api.shared.Type.Weekday value) {
        copyOnWrite();
        instance.setChangeTo(value);
        return this;
      }
      /**
       * <code>optional .shared.Weekday change_to = 5 [json_name = "changeTo"];</code>
       * @return This builder for chaining.
       */
      public Builder clearChangeTo() {
        copyOnWrite();
        instance.clearChangeTo();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schoolcalendar.v1.Event)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.schoolcalendar.v1.Type.Event();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "id_",
              "type_",
              "date_",
              "description_",
              "changeTo_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0004\u0002\f" +
                "\u0003\u1009\u0000\u0004\u0208\u0005\u100c\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.schoolcalendar.v1.Type.Event> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.schoolcalendar.v1.Type.Event.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.schoolcalendar.v1.Type.Event>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:schoolcalendar.v1.Event)
    private static final net.twinte.api.schoolcalendar.v1.Type.Event DEFAULT_INSTANCE;
    static {
      Event defaultInstance = new Event();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Event.class, defaultInstance);
    }

    public static net.twinte.api.schoolcalendar.v1.Type.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Event> PARSER;

    public static com.google.protobuf.Parser<Event> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
