// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: auth/v1/service.proto
//
package net.twinte.api.auth.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The following error codes are not stated explicitly in the each rpc, but may be returned.
 *    - shared.InvalidArgument
 *    - shared.Unauthenticated
 *    - shared.Unauthorized
 */
public interface AuthServiceClientInterface {
  public suspend fun getMe(request: Service.GetMeRequest, headers: Headers = emptyMap()): ResponseMessage<Service.GetMeResponse>

  public suspend fun deleteUserAuthentication(request: Service.DeleteUserAuthenticationRequest, headers: Headers = emptyMap()): ResponseMessage<Service.DeleteUserAuthenticationResponse>

  public suspend fun deleteAccount(request: Service.DeleteAccountRequest, headers: Headers = emptyMap()): ResponseMessage<Service.DeleteAccountResponse>
}
