// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/v1/service.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.auth.v1;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GetMeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.GetMeRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code auth.v1.GetMeRequest}
   */
  public  static final class GetMeRequest extends
      com.google.protobuf.GeneratedMessageLite<
          GetMeRequest, GetMeRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.GetMeRequest)
      GetMeRequestOrBuilder {
    private GetMeRequest() {
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Service.GetMeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Service.GetMeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.GetMeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Service.GetMeRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.GetMeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Service.GetMeRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.GetMeRequest)
        net.twinte.api.auth.v1.Service.GetMeRequestOrBuilder {
      // Construct using net.twinte.api.auth.v1.Service.GetMeRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:auth.v1.GetMeRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Service.GetMeRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Service.GetMeRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Service.GetMeRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Service.GetMeRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.GetMeRequest)
    private static final net.twinte.api.auth.v1.Service.GetMeRequest DEFAULT_INSTANCE;
    static {
      GetMeRequest defaultInstance = new GetMeRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetMeRequest.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Service.GetMeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetMeRequest> PARSER;

    public static com.google.protobuf.Parser<GetMeRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetMeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.GetMeResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     * @return The user.
     */
    net.twinte.api.auth.v1.Type.User getUser();
  }
  /**
   * Protobuf type {@code auth.v1.GetMeResponse}
   */
  public  static final class GetMeResponse extends
      com.google.protobuf.GeneratedMessageLite<
          GetMeResponse, GetMeResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.GetMeResponse)
      GetMeResponseOrBuilder {
    private GetMeResponse() {
    }
    private int bitField0_;
    public static final int USER_FIELD_NUMBER = 1;
    private net.twinte.api.auth.v1.Type.User user_;
    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     */
    @java.lang.Override
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     */
    @java.lang.Override
    public net.twinte.api.auth.v1.Type.User getUser() {
      return user_ == null ? net.twinte.api.auth.v1.Type.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setUser(net.twinte.api.auth.v1.Type.User value) {
      value.getClass();  // minimal bytecode null check
      user_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeUser(net.twinte.api.auth.v1.Type.User value) {
      value.getClass();  // minimal bytecode null check
      if (user_ != null &&
          user_ != net.twinte.api.auth.v1.Type.User.getDefaultInstance()) {
        user_ =
          net.twinte.api.auth.v1.Type.User.newBuilder(user_).mergeFrom(value).buildPartial();
      } else {
        user_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
     */
    private void clearUser() {
      user_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Service.GetMeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Service.GetMeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.GetMeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Service.GetMeResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.GetMeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Service.GetMeResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.GetMeResponse)
        net.twinte.api.auth.v1.Service.GetMeResponseOrBuilder {
      // Construct using net.twinte.api.auth.v1.Service.GetMeResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
       */
      @java.lang.Override
      public boolean hasUser() {
        return instance.hasUser();
      }
      /**
       * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
       */
      @java.lang.Override
      public net.twinte.api.auth.v1.Type.User getUser() {
        return instance.getUser();
      }
      /**
       * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
       */
      public Builder setUser(net.twinte.api.auth.v1.Type.User value) {
        copyOnWrite();
        instance.setUser(value);
        return this;
        }
      /**
       * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
       */
      public Builder setUser(
          net.twinte.api.auth.v1.Type.User.Builder builderForValue) {
        copyOnWrite();
        instance.setUser(builderForValue.build());
        return this;
      }
      /**
       * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
       */
      public Builder mergeUser(net.twinte.api.auth.v1.Type.User value) {
        copyOnWrite();
        instance.mergeUser(value);
        return this;
      }
      /**
       * <code>.auth.v1.User user = 1 [json_name = "user"];</code>
       */
      public Builder clearUser() {  copyOnWrite();
        instance.clearUser();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1.GetMeResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Service.GetMeResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "user_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Service.GetMeResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Service.GetMeResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Service.GetMeResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.GetMeResponse)
    private static final net.twinte.api.auth.v1.Service.GetMeResponse DEFAULT_INSTANCE;
    static {
      GetMeResponse defaultInstance = new GetMeResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GetMeResponse.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Service.GetMeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetMeResponse> PARSER;

    public static com.google.protobuf.Parser<GetMeResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DeleteUserAuthenticationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.DeleteUserAuthenticationRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The enum numeric value on the wire for provider.
     */
    int getProviderValue();
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    net.twinte.api.auth.v1.Type.Provider getProvider();
  }
  /**
   * Protobuf type {@code auth.v1.DeleteUserAuthenticationRequest}
   */
  public  static final class DeleteUserAuthenticationRequest extends
      com.google.protobuf.GeneratedMessageLite<
          DeleteUserAuthenticationRequest, DeleteUserAuthenticationRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.DeleteUserAuthenticationRequest)
      DeleteUserAuthenticationRequestOrBuilder {
    private DeleteUserAuthenticationRequest() {
    }
    public static final int PROVIDER_FIELD_NUMBER = 1;
    private int provider_;
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The enum numeric value on the wire for provider.
     */
    @java.lang.Override
    public int getProviderValue() {
      return provider_;
    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    @java.lang.Override
    public net.twinte.api.auth.v1.Type.Provider getProvider() {
      net.twinte.api.auth.v1.Type.Provider result = net.twinte.api.auth.v1.Type.Provider.forNumber(provider_);
      return result == null ? net.twinte.api.auth.v1.Type.Provider.UNRECOGNIZED : result;
    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @param value The enum numeric value on the wire for provider to set.
     */
    private void setProviderValue(int value) {
        provider_ = value;
    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @param value The provider to set.
     */
    private void setProvider(net.twinte.api.auth.v1.Type.Provider value) {
      provider_ = value.getNumber();

    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     */
    private void clearProvider() {

      provider_ = 0;
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.DeleteUserAuthenticationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.DeleteUserAuthenticationRequest)
        net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequestOrBuilder {
      // Construct using net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @return The enum numeric value on the wire for provider.
       */
      @java.lang.Override
      public int getProviderValue() {
        return instance.getProviderValue();
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @param value The provider to set.
       * @return This builder for chaining.
       */
      public Builder setProviderValue(int value) {
        copyOnWrite();
        instance.setProviderValue(value);
        return this;
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @return The provider.
       */
      @java.lang.Override
      public net.twinte.api.auth.v1.Type.Provider getProvider() {
        return instance.getProvider();
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @param value The enum numeric value on the wire for provider to set.
       * @return This builder for chaining.
       */
      public Builder setProvider(net.twinte.api.auth.v1.Type.Provider value) {
        copyOnWrite();
        instance.setProvider(value);
        return this;
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProvider() {
        copyOnWrite();
        instance.clearProvider();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1.DeleteUserAuthenticationRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "provider_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.DeleteUserAuthenticationRequest)
    private static final net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest DEFAULT_INSTANCE;
    static {
      DeleteUserAuthenticationRequest defaultInstance = new DeleteUserAuthenticationRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DeleteUserAuthenticationRequest.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DeleteUserAuthenticationRequest> PARSER;

    public static com.google.protobuf.Parser<DeleteUserAuthenticationRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DeleteUserAuthenticationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.DeleteUserAuthenticationResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code auth.v1.DeleteUserAuthenticationResponse}
   */
  public  static final class DeleteUserAuthenticationResponse extends
      com.google.protobuf.GeneratedMessageLite<
          DeleteUserAuthenticationResponse, DeleteUserAuthenticationResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.DeleteUserAuthenticationResponse)
      DeleteUserAuthenticationResponseOrBuilder {
    private DeleteUserAuthenticationResponse() {
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.DeleteUserAuthenticationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.DeleteUserAuthenticationResponse)
        net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponseOrBuilder {
      // Construct using net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:auth.v1.DeleteUserAuthenticationResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.DeleteUserAuthenticationResponse)
    private static final net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse DEFAULT_INSTANCE;
    static {
      DeleteUserAuthenticationResponse defaultInstance = new DeleteUserAuthenticationResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DeleteUserAuthenticationResponse.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Service.DeleteUserAuthenticationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DeleteUserAuthenticationResponse> PARSER;

    public static com.google.protobuf.Parser<DeleteUserAuthenticationResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DeleteAccountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.DeleteAccountRequest)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code auth.v1.DeleteAccountRequest}
   */
  public  static final class DeleteAccountRequest extends
      com.google.protobuf.GeneratedMessageLite<
          DeleteAccountRequest, DeleteAccountRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.DeleteAccountRequest)
      DeleteAccountRequestOrBuilder {
    private DeleteAccountRequest() {
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Service.DeleteAccountRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.DeleteAccountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Service.DeleteAccountRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.DeleteAccountRequest)
        net.twinte.api.auth.v1.Service.DeleteAccountRequestOrBuilder {
      // Construct using net.twinte.api.auth.v1.Service.DeleteAccountRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:auth.v1.DeleteAccountRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Service.DeleteAccountRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Service.DeleteAccountRequest> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Service.DeleteAccountRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Service.DeleteAccountRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.DeleteAccountRequest)
    private static final net.twinte.api.auth.v1.Service.DeleteAccountRequest DEFAULT_INSTANCE;
    static {
      DeleteAccountRequest defaultInstance = new DeleteAccountRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DeleteAccountRequest.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Service.DeleteAccountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DeleteAccountRequest> PARSER;

    public static com.google.protobuf.Parser<DeleteAccountRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DeleteAccountResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.DeleteAccountResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code auth.v1.DeleteAccountResponse}
   */
  public  static final class DeleteAccountResponse extends
      com.google.protobuf.GeneratedMessageLite<
          DeleteAccountResponse, DeleteAccountResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.DeleteAccountResponse)
      DeleteAccountResponseOrBuilder {
    private DeleteAccountResponse() {
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Service.DeleteAccountResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.DeleteAccountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Service.DeleteAccountResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.DeleteAccountResponse)
        net.twinte.api.auth.v1.Service.DeleteAccountResponseOrBuilder {
      // Construct using net.twinte.api.auth.v1.Service.DeleteAccountResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:auth.v1.DeleteAccountResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Service.DeleteAccountResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = null;
            java.lang.String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Service.DeleteAccountResponse> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Service.DeleteAccountResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Service.DeleteAccountResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.DeleteAccountResponse)
    private static final net.twinte.api.auth.v1.Service.DeleteAccountResponse DEFAULT_INSTANCE;
    static {
      DeleteAccountResponse defaultInstance = new DeleteAccountResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DeleteAccountResponse.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Service.DeleteAccountResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DeleteAccountResponse> PARSER;

    public static com.google.protobuf.Parser<DeleteAccountResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
