// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/v1/type.proto
// Protobuf Java Version: 4.30.2

package net.twinte.api.auth.v1;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code auth.v1.Provider}
   */
  public enum Provider
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>PROVIDER_UNSPECIFIED = 0;</code>
     */
    PROVIDER_UNSPECIFIED(0),
    /**
     * <code>PROVIDER_GOOGLE = 1;</code>
     */
    PROVIDER_GOOGLE(1),
    /**
     * <code>PROVIDER_APPLE = 2;</code>
     */
    PROVIDER_APPLE(2),
    /**
     * <code>PROVIDER_TWITTER = 3;</code>
     */
    PROVIDER_TWITTER(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PROVIDER_UNSPECIFIED = 0;</code>
     */
    public static final int PROVIDER_UNSPECIFIED_VALUE = 0;
    /**
     * <code>PROVIDER_GOOGLE = 1;</code>
     */
    public static final int PROVIDER_GOOGLE_VALUE = 1;
    /**
     * <code>PROVIDER_APPLE = 2;</code>
     */
    public static final int PROVIDER_APPLE_VALUE = 2;
    /**
     * <code>PROVIDER_TWITTER = 3;</code>
     */
    public static final int PROVIDER_TWITTER_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Provider valueOf(int value) {
      return forNumber(value);
    }

    public static Provider forNumber(int value) {
      switch (value) {
        case 0: return PROVIDER_UNSPECIFIED;
        case 1: return PROVIDER_GOOGLE;
        case 2: return PROVIDER_APPLE;
        case 3: return PROVIDER_TWITTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Provider>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Provider> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Provider>() {
            @java.lang.Override
            public Provider findValueByNumber(int number) {
              return Provider.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ProviderVerifier.INSTANCE;
    }

    private static final class ProviderVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new ProviderVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Provider.forNumber(number) != null;
            }
          };

    private final int value;

    private Provider(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:auth.v1.Provider)
  }

  public interface UserAuthenticationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.UserAuthentication)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The enum numeric value on the wire for provider.
     */
    int getProviderValue();
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    net.twinte.api.auth.v1.Type.Provider getProvider();

    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     * @return The socialId.
     */
    java.lang.String getSocialId();
    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     * @return The bytes for socialId.
     */
    com.google.protobuf.ByteString
        getSocialIdBytes();
  }
  /**
   * Protobuf type {@code auth.v1.UserAuthentication}
   */
  public  static final class UserAuthentication extends
      com.google.protobuf.GeneratedMessageLite<
          UserAuthentication, UserAuthentication.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.UserAuthentication)
      UserAuthenticationOrBuilder {
    private UserAuthentication() {
      socialId_ = "";
    }
    public static final int PROVIDER_FIELD_NUMBER = 1;
    private int provider_;
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The enum numeric value on the wire for provider.
     */
    @java.lang.Override
    public int getProviderValue() {
      return provider_;
    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    @java.lang.Override
    public net.twinte.api.auth.v1.Type.Provider getProvider() {
      net.twinte.api.auth.v1.Type.Provider result = net.twinte.api.auth.v1.Type.Provider.forNumber(provider_);
      return result == null ? net.twinte.api.auth.v1.Type.Provider.UNRECOGNIZED : result;
    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @param value The enum numeric value on the wire for provider to set.
     */
    private void setProviderValue(int value) {
        provider_ = value;
    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     * @param value The provider to set.
     */
    private void setProvider(net.twinte.api.auth.v1.Type.Provider value) {
      provider_ = value.getNumber();

    }
    /**
     * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
     */
    private void clearProvider() {

      provider_ = 0;
    }

    public static final int SOCIAL_ID_FIELD_NUMBER = 2;
    private java.lang.String socialId_;
    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     * @return The socialId.
     */
    @java.lang.Override
    public java.lang.String getSocialId() {
      return socialId_;
    }
    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     * @return The bytes for socialId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSocialIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(socialId_);
    }
    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     * @param value The socialId to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setSocialId(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      socialId_ = value;
    }
    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     */
    private void clearSocialId() {

      socialId_ = getDefaultInstance().getSocialId();
    }
    /**
     * <code>string social_id = 2 [json_name = "socialId"];</code>
     * @param value The bytes for socialId to set.
     */
    private void setSocialIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      socialId_ = value.toStringUtf8();

    }

    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Type.UserAuthentication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Type.UserAuthentication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Type.UserAuthentication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Type.UserAuthentication prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.UserAuthentication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Type.UserAuthentication, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.UserAuthentication)
        net.twinte.api.auth.v1.Type.UserAuthenticationOrBuilder {
      // Construct using net.twinte.api.auth.v1.Type.UserAuthentication.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @return The enum numeric value on the wire for provider.
       */
      @java.lang.Override
      public int getProviderValue() {
        return instance.getProviderValue();
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @param value The provider to set.
       * @return This builder for chaining.
       */
      public Builder setProviderValue(int value) {
        copyOnWrite();
        instance.setProviderValue(value);
        return this;
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @return The provider.
       */
      @java.lang.Override
      public net.twinte.api.auth.v1.Type.Provider getProvider() {
        return instance.getProvider();
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @param value The enum numeric value on the wire for provider to set.
       * @return This builder for chaining.
       */
      public Builder setProvider(net.twinte.api.auth.v1.Type.Provider value) {
        copyOnWrite();
        instance.setProvider(value);
        return this;
      }
      /**
       * <code>.auth.v1.Provider provider = 1 [json_name = "provider"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProvider() {
        copyOnWrite();
        instance.clearProvider();
        return this;
      }

      /**
       * <code>string social_id = 2 [json_name = "socialId"];</code>
       * @return The socialId.
       */
      @java.lang.Override
      public java.lang.String getSocialId() {
        return instance.getSocialId();
      }
      /**
       * <code>string social_id = 2 [json_name = "socialId"];</code>
       * @return The bytes for socialId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSocialIdBytes() {
        return instance.getSocialIdBytes();
      }
      /**
       * <code>string social_id = 2 [json_name = "socialId"];</code>
       * @param value The socialId to set.
       * @return This builder for chaining.
       */
      public Builder setSocialId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSocialId(value);
        return this;
      }
      /**
       * <code>string social_id = 2 [json_name = "socialId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSocialId() {
        copyOnWrite();
        instance.clearSocialId();
        return this;
      }
      /**
       * <code>string social_id = 2 [json_name = "socialId"];</code>
       * @param value The bytes for socialId to set.
       * @return This builder for chaining.
       */
      public Builder setSocialIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSocialIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1.UserAuthentication)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Type.UserAuthentication();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "provider_",
              "socialId_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Type.UserAuthentication> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Type.UserAuthentication.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Type.UserAuthentication>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.UserAuthentication)
    private static final net.twinte.api.auth.v1.Type.UserAuthentication DEFAULT_INSTANCE;
    static {
      UserAuthentication defaultInstance = new UserAuthentication();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserAuthentication.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Type.UserAuthentication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserAuthentication> PARSER;

    public static com.google.protobuf.Parser<UserAuthentication> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.v1.User)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    net.twinte.api.shared.Type.UUID getId();

    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    java.util.List<net.twinte.api.auth.v1.Type.UserAuthentication> 
        getAuthenticationsList();
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    net.twinte.api.auth.v1.Type.UserAuthentication getAuthentications(int index);
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    int getAuthenticationsCount();
  }
  /**
   * Protobuf type {@code auth.v1.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageLite<
          User, User.Builder> implements
      // @@protoc_insertion_point(message_implements:auth.v1.User)
      UserOrBuilder {
    private User() {
      authentications_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private net.twinte.api.shared.Type.UUID id_;
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.Override
    public net.twinte.api.shared.Type.UUID getId() {
      return id_ == null ? net.twinte.api.shared.Type.UUID.getDefaultInstance() : id_;
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setId(net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      id_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
    private void mergeId(net.twinte.api.shared.Type.UUID value) {
      value.getClass();  // minimal bytecode null check
      if (id_ != null &&
          id_ != net.twinte.api.shared.Type.UUID.getDefaultInstance()) {
        id_ =
          net.twinte.api.shared.Type.UUID.newBuilder(id_).mergeFrom(value).buildPartial();
      } else {
        id_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.shared.UUID id = 1 [json_name = "id"];</code>
     */
    private void clearId() {
      id_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int AUTHENTICATIONS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<net.twinte.api.auth.v1.Type.UserAuthentication> authentications_;
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    @java.lang.Override
    public java.util.List<net.twinte.api.auth.v1.Type.UserAuthentication> getAuthenticationsList() {
      return authentications_;
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    public java.util.List<? extends net.twinte.api.auth.v1.Type.UserAuthenticationOrBuilder> 
        getAuthenticationsOrBuilderList() {
      return authentications_;
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    @java.lang.Override
    public int getAuthenticationsCount() {
      return authentications_.size();
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    @java.lang.Override
    public net.twinte.api.auth.v1.Type.UserAuthentication getAuthentications(int index) {
      return authentications_.get(index);
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    public net.twinte.api.auth.v1.Type.UserAuthenticationOrBuilder getAuthenticationsOrBuilder(
        int index) {
      return authentications_.get(index);
    }
    private void ensureAuthenticationsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<net.twinte.api.auth.v1.Type.UserAuthentication> tmp = authentications_;
      if (!tmp.isModifiable()) {
        authentications_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setAuthentications(
        int index, net.twinte.api.auth.v1.Type.UserAuthentication value) {
      value.getClass();  // minimal bytecode null check
      ensureAuthenticationsIsMutable();
      authentications_.set(index, value);
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addAuthentications(net.twinte.api.auth.v1.Type.UserAuthentication value) {
      value.getClass();  // minimal bytecode null check
      ensureAuthenticationsIsMutable();
      authentications_.add(value);
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void addAuthentications(
        int index, net.twinte.api.auth.v1.Type.UserAuthentication value) {
      value.getClass();  // minimal bytecode null check
      ensureAuthenticationsIsMutable();
      authentications_.add(index, value);
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    private void addAllAuthentications(
        java.lang.Iterable<? extends net.twinte.api.auth.v1.Type.UserAuthentication> values) {
      ensureAuthenticationsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, authentications_);
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    private void clearAuthentications() {
      authentications_ = emptyProtobufList();
    }
    /**
     * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
     */
    private void removeAuthentications(int index) {
      ensureAuthenticationsIsMutable();
      authentications_.remove(index);
    }

    public static net.twinte.api.auth.v1.Type.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static net.twinte.api.auth.v1.Type.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static net.twinte.api.auth.v1.Type.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static net.twinte.api.auth.v1.Type.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(net.twinte.api.auth.v1.Type.User prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code auth.v1.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          net.twinte.api.auth.v1.Type.User, Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.v1.User)
        net.twinte.api.auth.v1.Type.UserOrBuilder {
      // Construct using net.twinte.api.auth.v1.Type.User.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      @java.lang.Override
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      @java.lang.Override
      public net.twinte.api.shared.Type.UUID getId() {
        return instance.getId();
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder setId(net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.setId(value);
        return this;
        }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder setId(
          net.twinte.api.shared.Type.UUID.Builder builderForValue) {
        copyOnWrite();
        instance.setId(builderForValue.build());
        return this;
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder mergeId(net.twinte.api.shared.Type.UUID value) {
        copyOnWrite();
        instance.mergeId(value);
        return this;
      }
      /**
       * <code>.shared.UUID id = 1 [json_name = "id"];</code>
       */
      public Builder clearId() {  copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      @java.lang.Override
      public java.util.List<net.twinte.api.auth.v1.Type.UserAuthentication> getAuthenticationsList() {
        return java.util.Collections.unmodifiableList(
            instance.getAuthenticationsList());
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      @java.lang.Override
      public int getAuthenticationsCount() {
        return instance.getAuthenticationsCount();
      }/**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      @java.lang.Override
      public net.twinte.api.auth.v1.Type.UserAuthentication getAuthentications(int index) {
        return instance.getAuthentications(index);
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder setAuthentications(
          int index, net.twinte.api.auth.v1.Type.UserAuthentication value) {
        copyOnWrite();
        instance.setAuthentications(index, value);
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder setAuthentications(
          int index, net.twinte.api.auth.v1.Type.UserAuthentication.Builder builderForValue) {
        copyOnWrite();
        instance.setAuthentications(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder addAuthentications(net.twinte.api.auth.v1.Type.UserAuthentication value) {
        copyOnWrite();
        instance.addAuthentications(value);
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder addAuthentications(
          int index, net.twinte.api.auth.v1.Type.UserAuthentication value) {
        copyOnWrite();
        instance.addAuthentications(index, value);
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder addAuthentications(
          net.twinte.api.auth.v1.Type.UserAuthentication.Builder builderForValue) {
        copyOnWrite();
        instance.addAuthentications(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder addAuthentications(
          int index, net.twinte.api.auth.v1.Type.UserAuthentication.Builder builderForValue) {
        copyOnWrite();
        instance.addAuthentications(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder addAllAuthentications(
          java.lang.Iterable<? extends net.twinte.api.auth.v1.Type.UserAuthentication> values) {
        copyOnWrite();
        instance.addAllAuthentications(values);
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder clearAuthentications() {
        copyOnWrite();
        instance.clearAuthentications();
        return this;
      }
      /**
       * <code>repeated .auth.v1.UserAuthentication authentications = 2 [json_name = "authentications"];</code>
       */
      public Builder removeAuthentications(int index) {
        copyOnWrite();
        instance.removeAuthentications(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:auth.v1.User)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new net.twinte.api.auth.v1.Type.User();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "id_",
              "authentications_",
              net.twinte.api.auth.v1.Type.UserAuthentication.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u1009\u0000\u0002" +
                "\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<net.twinte.api.auth.v1.Type.User> parser = PARSER;
          if (parser == null) {
            synchronized (net.twinte.api.auth.v1.Type.User.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<net.twinte.api.auth.v1.Type.User>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:auth.v1.User)
    private static final net.twinte.api.auth.v1.Type.User DEFAULT_INSTANCE;
    static {
      User defaultInstance = new User();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        User.class, defaultInstance);
    }

    public static net.twinte.api.auth.v1.Type.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<User> PARSER;

    public static com.google.protobuf.Parser<User> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
